#ARCHSPACE MODULE CONFIGURATION

#Load the module
<IfModule !mod_as.c>
	LoadModule as_module	extramodules/mod_as.so
<IfModule mod_as.c>

#Set the handlers
<Location '/archspace'>
 Options FollowSymLinks
 Order allow,deny
 Allow from all
 AddHandler archspace-handler .as
 AddHandler archspace-script  .as
 AddHandler application/x-archspace .as
</Location>

# Set the values
ArchspaceWebServerID 200
ArchspaceGameServerName localhost
ArchspaceGameServerPort 12350
ArchspaceGameServerDownMessage /usr/src/archspace/ServerDownMessage
ArchspaceGameServerMaintenanceMessage /usr/src/archspace/ServerMaintenanceMessage
ArchspaceRedirectURL /not_logged_in.html
</IfModule>

