#!/usr/bin/perl

$DATABASE = "../src/org/DB/archcave.sql";
$OUTDIR = "../src/org/archcave/classes/";

$OBJECT_IMPORTS = "package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;\n";
$OBJECT_HEADER = "//Object generated by zbyte\'s sql to java script";

$LIST_IMPORTS = "package org.archcave.classes;
import java.util.Vector;\n";
$LIST_HEADER = "//List generated by zbyte\'s sql to java script";

$TABLE_IMPORTS = "package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;\n";
$TABLE_HEADER = "//Table generated by zbyte\'s sql to java script";

$CLASS_PREFIX = "AC";
$GETSQLQUERY1 = '	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO ';
$GETSQLQUERY2 = ' "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE ';
$GETSQLQUERY3 = ' SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM ';
$GETSQLQUERY4 = ' WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}
';
$OBJECT_INNATE_INHERIT = " {\n";
$LIST_INNATE_INHERIT = " {\n";
$TABLE_INNATE_INHERIT = " implements JStore {\n\n";
$OBJECT_INNATE_VARS = "	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;\n";
$TABLE_INNATE_VARS = "	private int max_id;\n	private java.util.Stack SQLsyncObjects = new java.util.Stack();\n\n";
$GETSQLUPDATESTATEMENTS = "	private String getSQLupdatestatements() {
		String result = new String();\n";
$GETSQLINSERTSTATEMENTS = "	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();\n";
$SETSQLACTION = "	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}\n";
$CAP_UPDATESTATEMENT = "		result = result.substring(0,result.length()-2);
		return result;
	}\n";
$CAP_INSERTSTATEMENT = '		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}'."\n";

$CORE = 'public class '.$CLASS_PREFIX.'Core {
	private static JStoreStation mJstoreStation;';
$CORE_CONSTUCTOR = '	public '.$CLASS_PREFIX.'Core(java.lang.String aConnectionUrl) {
	mJstoreStation = new JStoreStation(aConnectionUrl);';
$CORE_SQL_SYNC = '	public void '.$CLASS_PREFIX.'Sync() {
';
$CORE_LOAD = '	public void '.$CLASS_PREFIX.'Load() {
';
$CORE_UNLOAD = '	public void '.$CLASS_PREFIX.'UnLoad() {
';


my $output;
my $imports;

open(FILEREAD, "< ".$DATABASE);
@lines = <FILEREAD>;
for ($index=0; $index<@lines; $index++) {
	$line = @lines[$index];
	$position1 = (index lc $line, 'table ');
	if ($position1 > -1)
	{
		$sqltable = substr($line, $position1+6, length($line)-$position1-9);
		$table = get_varname($sqltable);
		$tableclass = 'public class '.$CLASS_PREFIX.$table."Table extends ".$CLASS_PREFIX.$table."List".$TABLE_INNATE_INHERIT.$TABLE_INNATE_VARS;
		$listclass = 'public class '.$CLASS_PREFIX.$table."List".$LIST_INNATE_INHERIT.$INNATE_VARS;
		$objectclass = 'public class '.$CLASS_PREFIX.$table.$OBJECT_INNATE_INHERIT.$OBJECT_INNATE_VARS;
		$flag = 0;
		$enum = "";
		$imports = "";
		$setfunctions = "";
		$getfunctions = "";
		$updatestatements = "";
		$insertstatements = "";
		$findfunctions = "";
		$objectconstructor = "";
		$tableloadsql = "";
		$CORE = $CORE.'	public static '.$CLASS_PREFIX.$Table.'Table m'.$CLASS_PREFIX.$Table.";\n";
		$CORE_CONSTRUCTOR = $CORE_CONSTRUCTOR.'		m'.$CLASS_PREFIX.$Table.' = new '.$CLASS_PREFIX.$Table."();\n";
		$CORE_SQL_SYNC = $CORE_SQL_SYNC."		mJStoreStation.process(m".$CLASS_PREFIX.$Table.");\n";
		$objectsqlconstructor = "	public ".$CLASS_PREFIX.$table."(java.sql.ResultSet SQLRes) {
        	try {\n";
		$tableclass = $tableclass."	public ".$CLASS_PREFIX.$table."Table() {
	} 

	public void remove(".$CLASS_PREFIX.$table." a".$CLASS_PREFIX.$table.") {
		a".$CLASS_PREFIX.$table.".setSQLaction(3);
		appendSQLsync(a".$CLASS_PREFIX.$table.");
		this.".$CLASS_PREFIX.$table."Vector.remove(a".$CLASS_PREFIX.$table.");
	}

	public ".$CLASS_PREFIX.$table." create() {
		max_id++;
		".$CLASS_PREFIX.$table." a".$CLASS_PREFIX.$table." = new ".$CLASS_PREFIX.$table."(max_id);
		".$CLASS_PREFIX.$table."Vector.add(a".$CLASS_PREFIX.$table."); //bypass sort algorithm
		return a".$CLASS_PREFIX.$table.";
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		".$CLASS_PREFIX.$table." current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (".$CLASS_PREFIX.$table.")SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log(\"SQLException: \" + ex.getMessage()); 
			JLog.log(\"SQLState: \" + ex.getSQLState()); 
			JLog.log(\"VendorError: \" + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(".$CLASS_PREFIX.$table." a".$CLASS_PREFIX.$table.") {
		SQLsyncObjects.push(a".$CLASS_PREFIX.$table.");
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}";
		$listclass = $listclass."	protected Vector ".$CLASS_PREFIX.$table."Vector = new Vector();
	
	public void add(".$CLASS_PREFIX.$table." a".$CLASS_PREFIX.$table.") {
		if (".$CLASS_PREFIX.$table."Vector.size() == 0) {
			".$CLASS_PREFIX.$table."Vector.add(0, a".$CLASS_PREFIX.$table.");
			return;
		}
		int middle = (".$CLASS_PREFIX.$table."Vector.size()-1)/2;
		int index = middle;
		".$CLASS_PREFIX.$table." current = (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(index);
		while ((index > 0)&&(current.getId() > a".$CLASS_PREFIX.$table.".getId()))
		{
			index--;
			current = (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(index);
		}
		if (index==middle)
		{
			while ((index < ".$CLASS_PREFIX.$table."Vector.size() - 1 )&&(current.getId() < a".$CLASS_PREFIX.$table.".getId()))
			{
				index++;
				current = (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(index);
			}
		}
		".$CLASS_PREFIX.$table."Vector.add(index, a".$CLASS_PREFIX.$table.");
	}
	
	public ".$CLASS_PREFIX.$table." fetch(int aID) {
		if (".$CLASS_PREFIX.$table."Vector.size() == 0) return null;
		int middle = (".$CLASS_PREFIX.$table."Vector.size()-1)/2;
		int index = middle;
		".$CLASS_PREFIX.$table." current = (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(index);
		}
		if (index==middle)
		{
			while ((index < ".$CLASS_PREFIX.$table."Vector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.".$CLASS_PREFIX.$table."Vector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(".$CLASS_PREFIX.$table." a".$CLASS_PREFIX.$table.") {//done
		this.".$CLASS_PREFIX.$table."Vector.remove(a".$CLASS_PREFIX.$table.");
	}
	
	public int length() {//done
		return this.".$CLASS_PREFIX.$table."Vector.size();
	}
	
	public ".$CLASS_PREFIX.$table." get(int aNumber) {//done
		return (".$CLASS_PREFIX.$table.")".$CLASS_PREFIX.$table."Vector.get(aNumber);
	}";
		$tablelink = "	public static ".$CLASS_PREFIX.$table."Table mTable;";
		$vars = 0;
		for ($index=$index; (($index<@lines) && ($flag==0)); $index++) {
			$line = @lines[$index];
			if (-1 < (index lc $line, ' not null')) {
				$line =~ s/^\s*//; 
				$position1 = (index $line, ' ');
				my $sqlvarname = substr($line, 0, $position1);
				my $varname = get_varname($sqlvarname);
				my $evarname = uc "e_".$varname;
				$vartype = get_vartype($line);
				$objectclass = $objectclass.'	private '.$vartype.' s'.$varname.";\n";
				$tableloadsql = $tableloadsql.$sqlvarname.", ";
				if ( $vartype ne 'org.archcave.libs.Jhash') {
					$insertstatements = $insertstatements.'		if (mStoreFlags.get('.$evarname.')) { vars += "'.$sqlvarname.',"; values += s'.$varname.' + ",";}'."\n";
				} else {
					$insertstatements = $insertstatements.'		if (mStoreFlags.get('.$evarname.')) { vars += "'.$sqlvarname.',"; values += s'.$varname.'.getSQLValue() + ",";}'."\n";
				}
				$setfunctions = $setfunctions.'	public void set'.$varname.'('.$vartype.' a'.$varname.') {
		this.mStoreFlags.set('.$evarname.');
		this.setSQLaction(2);
		this.s'.$varname.' = a'.$varname.';
	}'."\n\n";
				$enum = $enum.'	public static final short '.$evarname.'='.$vars.";\n";
				$getfunctions = $getfunctions."\n".'	public '.$vartype.' get'.$varname.'() {
		return s'.$varname.';
	}'."\n";
				$objectsqlconstructor = $objectsqlconstructor."			s".$varname." = ".get_sqlconstructor($vartype, $evarname);
				if (lc $varname ne 'id') { 
					if ( $vartype ne 'org.archcave.libs.Jhash') {
						$updatestatements = $updatestatements.'		if (mStoreFlags.get('.$evarname.')) result += " '.$sqlvarname.'="+s'.$varname.' + ",";'."\n";
					} else {
						$updatestatements = $updatestatements.'		if (mStoreFlags.get('.$evarname.')) result += " '.$sqlvarname.'="+s'.$varname.'.getSQLValue() + ",";'."\n";
					}
					
					$findfunctions = $findfunctions."\n\n".'	public '.$CLASS_PREFIX.$table.'List findBy'.$varname.'('.$vartype.' a'.$varname.') {
		'.$CLASS_PREFIX.$table.'List a'.$CLASS_PREFIX.$table.'List = new '.$CLASS_PREFIX.$table.'List();
		'.$CLASS_PREFIX.$table.' current;
		for (int i = 0; i < this.'.$CLASS_PREFIX.$table.'Vector.size(); i++) {
			current = ('.$CLASS_PREFIX.$table.')this.'.$CLASS_PREFIX.$table.'Vector.get(i);
			';
			if ($vartype eq 'java.lang.String') {
				$findfunctions = $findfunctions.'if (a'.$varname.'.equals(current.get'.$varname.'())) {';
			} else {
				$findfunctions = $findfunctions.'if (a'.$varname.' == current.get'.$varname.'()) {';
			}
			$findfunctions = $findfunctions.'
				a'.$CLASS_PREFIX.$table.'List.add(current);
			}
		}
		return a'.$CLASS_PREFIX.$table.'List;
	}'; } else {
				$objectconstructor = '	public '.$CLASS_PREFIX.$table.'('.$vartype.' aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}'."\n";
	}
				$vars++;
			} else {
			if (-1 < (index $line, ');')) {
				$updatestatements = $GETSQLUPDATESTATEMENTS.$updatestatements.$CAP_UPDATESTATEMENT;
				$insertstatements = $GETSQLINSERTSTATEMENTS.$insertstatements.$CAP_INSERTSTATEMENT;
				$getsqlquery = $GETSQLQUERY1.$sqltable.$GETSQLQUERY2.$sqltable.$GETSQLQUERY3.$sqltable.$GETSQLQUERY4;
				$objectsqlconstructor = $objectsqlconstructor."		} catch (SQLException ex) {
			// handle any errors 
			JLog.log(\"SQLException: \" + ex.getMessage()); 
			JLog.log(\"SQLState: \" + ex.getSQLState()); 
			JLog.log(\"VendorError: \" + ex.getErrorCode()); 
		}
	}\n";
				$objectclass = $OBJECT_IMPORTS.get_imports()."\n".$OBJECT_HEADER."\n".$objectclass."\n".$tablelink."\n".$enum."\n".$objectconstructor."\n".$objectsqlconstructor."\n".$updatestatements."\n".$insertstatements."\n".$getsqlquery."\n".$SETSQLACTION."\n".$setfunctions.$getfunctions."}\n\n";
				$listclass = $LIST_IMPORTS.get_imports()."\n".$LIST_HEADER."\n".$listclass.$findfunctions."\n}\n\n";
				$tableclass = $TABLE_IMPORTS.get_imports()."\n".$TABLE_HEADER."\n".$tableclass."\n\n	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery(\"SELECT ".substr($tableloadsql, 0, -2)." FROM ".lcfirst $table." ORDER BY id\");
			".$CLASS_PREFIX.$table." loadedSQL".$CLASS_PREFIX.$table.";
			while (res.next()) {
				loadedSQL".$CLASS_PREFIX.$table." = new ".$CLASS_PREFIX.$table."(res);
				".$CLASS_PREFIX.$table."Vector.add(loadedSQL".$CLASS_PREFIX.$table."); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log(\"SQLException: \" + ex.getMessage()); 
			JLog.log(\"SQLState: \" + ex.getSQLState()); 
			JLog.log(\"VendorError: \" + ex.getErrorCode()); 
		}
	}\n}\n\n";
				open(FILEWRITE, "> ".$OUTDIR.$CLASS_PREFIX.$table.".java");
				print FILEWRITE $objectclass;
				close(FILEWRITE);
				open(FILEWRITE, "> ".$OUTDIR.$CLASS_PREFIX.$table."List.java");
				print FILEWRITE $listclass;
				close(FILEWRITE);
				open(FILEWRITE, "> ".$OUTDIR.$CLASS_PREFIX.$table."Table.java");
				print FILEWRITE $tableclass;
				close(FILEWRITE);
				$output = $output.$objectclass.$listclass.$tableclass;
				$flag = 1;
			}}
		}
		
	}
}
close(FILEREAD);
print $output;

sub get_vartype {
	$line = $_[0];
	if (-1 < (index lc $line, '_hash ')) {
		return 'org.archcave.libs.JHash';
	}
	if ((-1 < (index lc $line, ' char'))||(-1 < (index lc $line, ' blob'))||(-1 < (index lc $line, ' text'))||(-1 < (index lc $line, ' enum'))||(-1 < (index lc $line, ' set'))||(-1 < (index lc $line, ' varchar'))) {
		return 'java.lang.String';
	}
	if (-1 < (index lc $line, ' date')) {
		return 'java.sql.Date';
	}
	if (-1 < (index lc $line, ' timestamp')) {
		return 'java.sql.Timestamp';
	}
	if ((-1 < (index lc $line, ' float'))||(-1 < (index lc $line, ' double'))) {
		return 'java.lang.Double';
	}
	if ((-1 < (index lc $line, ' decimal'))||(-1 < (index lc $line, ' double precision'))) {
		return 'java.math.BigDecimal';
	}
	if (-1 < (index lc $line, ' tinyint')) {
		if (-1 == (index lc $line, ' unsigned')) {
			return 'byte';
		} else {
			return 'short';
		}
	}
	if (-1 < (index lc $line, ' mediumint')) {
		return 'int';
	}
	if (-1 < (index lc $line, ' smallint')) {
		if (-1 == (index lc $line, ' unsigned')) {
			return 'short';
		} else {
			return 'int';
		}
	}
	if (-1 < (index lc $line, ' bigint')) {
		if (-1 < (index $line, ' unsigned')) {
			return 'java.math.BigInteger';
		} else {
			return 'long';
		}
	} else {
		if (-1 < (index lc $line, ' unsigned')) {
			return 'long';
		} else {
			return 'int';
		}
	}
}

sub get_varname {
	my @words = split(/_/, $_[0]);
	my $varname;
	foreach (@words) {
		$varname = $varname.ucfirst $_;
	}
	return $varname;
}

sub get_sqlconstructor {
	my $vartype = $_[0];
	my $varname = $_[1];
	
	if ($vartype eq 'org.archcave.libs.JHash') {
		$imports = $imports."\nimport org.archcave.libs.JHash;";
		return "new JHash(SQLRes.getObject(".$varname.").toString());\n";
	}
	if ($vartype eq 'java.lang.String') {
		return "SQLRes.getObject(".$varname.").toString();\n";
	} 
	if ($vartype eq 'java.sql.Date') {
		$imports = $imports."\nimport java.sql.Date;";
		return "new java.sql.Date((long)Integer.parseInt(SQLRes.getObject(".$varname.").toString()));\n";
	}
	if ($vartype eq 'java.sql.Timestamp') {
		$imports = $imports."\nimport java.sql.Timestamp;";
		return "new java.sql.Timestamp((long)Integer.parseInt(SQLRes.getObject(".$varname.").toString()));\n";
	}
	if ($vartype eq 'java.lang.Double') {
		return "new java.lang.Double(SQLRes.getObject(".$varname.").toString());\n";
	}
	if ($vartype eq 'java.math.BigDecimal') {
		$imports = $imports."\nimport java.math.BigDecimal;";
		return "new java.math.BigDecimal(SQLRes.getObject(".$varname.").toString());\n";
	}
	if ($vartype eq 'java.math.BigInteger') {
		$imports = $imports."\nimport java.math.BigInteger;";
		return "new BigInteger(SQLRes.getObject(".$varname.").toString());\n";
	}
	return "(".$vartype.")Integer.parseInt(SQLRes.getObject(".$varname.").toString());\n";
}

sub get_imports {
	@importlist = split(/\n/, $imports);
	my @finallist;
	my $finalimports;
	foreach (@importlist) {
		$flag = 0;
		$possible_import = $_;
		foreach (@finallist) {
			if ($_ eq $possible_import) {$flag = 1;}
		}
		if ($flag == 0) {
			push @finallist, $possible_import;
			$finalimports = $finalimports.$possible_import;
		}
	}
	return $finalimports."\n";
}
