package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACDesigns {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sOwnerId;
	private java.lang.String sName;
	private byte sChasis;
	private short sWeapon1Id;
	private short sWeapon2Id;
	private short sWeapon3Id;
	private short sArmor1Id;
	private short sArmor2Id;
	private short sArmor3Id;
	private short sSpecial1Id;
	private short sSpecial2Id;
	private short sSpecial3Id;

	public static ACDesignsTable mTable;
	public static final short E_ID=0;
	public static final short E_OWNERID=1;
	public static final short E_NAME=2;
	public static final short E_CHASIS=3;
	public static final short E_WEAPON1ID=4;
	public static final short E_WEAPON2ID=5;
	public static final short E_WEAPON3ID=6;
	public static final short E_ARMOR1ID=7;
	public static final short E_ARMOR2ID=8;
	public static final short E_ARMOR3ID=9;
	public static final short E_SPECIAL1ID=10;
	public static final short E_SPECIAL2ID=11;
	public static final short E_SPECIAL3ID=12;

	public ACDesigns(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACDesigns(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OWNERID).toString());
			sName = SQLRes.getObject(E_NAME).toString();
			sChasis = (byte)Integer.parseInt(SQLRes.getObject(E_CHASIS).toString());
			sWeapon1Id = (short)Integer.parseInt(SQLRes.getObject(E_WEAPON1ID).toString());
			sWeapon2Id = (short)Integer.parseInt(SQLRes.getObject(E_WEAPON2ID).toString());
			sWeapon3Id = (short)Integer.parseInt(SQLRes.getObject(E_WEAPON3ID).toString());
			sArmor1Id = (short)Integer.parseInt(SQLRes.getObject(E_ARMOR1ID).toString());
			sArmor2Id = (short)Integer.parseInt(SQLRes.getObject(E_ARMOR2ID).toString());
			sArmor3Id = (short)Integer.parseInt(SQLRes.getObject(E_ARMOR3ID).toString());
			sSpecial1Id = (short)Integer.parseInt(SQLRes.getObject(E_SPECIAL1ID).toString());
			sSpecial2Id = (short)Integer.parseInt(SQLRes.getObject(E_SPECIAL2ID).toString());
			sSpecial3Id = (short)Integer.parseInt(SQLRes.getObject(E_SPECIAL3ID).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_OWNERID)) result += " owner_id="+sOwnerId + ",";
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_CHASIS)) result += " chasis="+sChasis + ",";
		if (mStoreFlags.get(E_WEAPON1ID)) result += " weapon1_id="+sWeapon1Id + ",";
		if (mStoreFlags.get(E_WEAPON2ID)) result += " weapon2_id="+sWeapon2Id + ",";
		if (mStoreFlags.get(E_WEAPON3ID)) result += " weapon3_id="+sWeapon3Id + ",";
		if (mStoreFlags.get(E_ARMOR1ID)) result += " armor1_id="+sArmor1Id + ",";
		if (mStoreFlags.get(E_ARMOR2ID)) result += " armor2_id="+sArmor2Id + ",";
		if (mStoreFlags.get(E_ARMOR3ID)) result += " armor3_id="+sArmor3Id + ",";
		if (mStoreFlags.get(E_SPECIAL1ID)) result += " special1_id="+sSpecial1Id + ",";
		if (mStoreFlags.get(E_SPECIAL2ID)) result += " special2_id="+sSpecial2Id + ",";
		if (mStoreFlags.get(E_SPECIAL3ID)) result += " special3_id="+sSpecial3Id + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_OWNERID)) { vars += "owner_id,"; values += sOwnerId + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_CHASIS)) { vars += "chasis,"; values += sChasis + ",";}
		if (mStoreFlags.get(E_WEAPON1ID)) { vars += "weapon1_id,"; values += sWeapon1Id + ",";}
		if (mStoreFlags.get(E_WEAPON2ID)) { vars += "weapon2_id,"; values += sWeapon2Id + ",";}
		if (mStoreFlags.get(E_WEAPON3ID)) { vars += "weapon3_id,"; values += sWeapon3Id + ",";}
		if (mStoreFlags.get(E_ARMOR1ID)) { vars += "armor1_id,"; values += sArmor1Id + ",";}
		if (mStoreFlags.get(E_ARMOR2ID)) { vars += "armor2_id,"; values += sArmor2Id + ",";}
		if (mStoreFlags.get(E_ARMOR3ID)) { vars += "armor3_id,"; values += sArmor3Id + ",";}
		if (mStoreFlags.get(E_SPECIAL1ID)) { vars += "special1_id,"; values += sSpecial1Id + ",";}
		if (mStoreFlags.get(E_SPECIAL2ID)) { vars += "special2_id,"; values += sSpecial2Id + ",";}
		if (mStoreFlags.get(E_SPECIAL3ID)) { vars += "special3_id,"; values += sSpecial3Id + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO designs "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE designs SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM designs WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setOwnerId(int aOwnerId) {
		this.mStoreFlags.set(E_OWNERID);
		this.setSQLaction(2);
		this.sOwnerId = aOwnerId;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setChasis(byte aChasis) {
		this.mStoreFlags.set(E_CHASIS);
		this.setSQLaction(2);
		this.sChasis = aChasis;
	}

	public void setWeapon1Id(short aWeapon1Id) {
		this.mStoreFlags.set(E_WEAPON1ID);
		this.setSQLaction(2);
		this.sWeapon1Id = aWeapon1Id;
	}

	public void setWeapon2Id(short aWeapon2Id) {
		this.mStoreFlags.set(E_WEAPON2ID);
		this.setSQLaction(2);
		this.sWeapon2Id = aWeapon2Id;
	}

	public void setWeapon3Id(short aWeapon3Id) {
		this.mStoreFlags.set(E_WEAPON3ID);
		this.setSQLaction(2);
		this.sWeapon3Id = aWeapon3Id;
	}

	public void setArmor1Id(short aArmor1Id) {
		this.mStoreFlags.set(E_ARMOR1ID);
		this.setSQLaction(2);
		this.sArmor1Id = aArmor1Id;
	}

	public void setArmor2Id(short aArmor2Id) {
		this.mStoreFlags.set(E_ARMOR2ID);
		this.setSQLaction(2);
		this.sArmor2Id = aArmor2Id;
	}

	public void setArmor3Id(short aArmor3Id) {
		this.mStoreFlags.set(E_ARMOR3ID);
		this.setSQLaction(2);
		this.sArmor3Id = aArmor3Id;
	}

	public void setSpecial1Id(short aSpecial1Id) {
		this.mStoreFlags.set(E_SPECIAL1ID);
		this.setSQLaction(2);
		this.sSpecial1Id = aSpecial1Id;
	}

	public void setSpecial2Id(short aSpecial2Id) {
		this.mStoreFlags.set(E_SPECIAL2ID);
		this.setSQLaction(2);
		this.sSpecial2Id = aSpecial2Id;
	}

	public void setSpecial3Id(short aSpecial3Id) {
		this.mStoreFlags.set(E_SPECIAL3ID);
		this.setSQLaction(2);
		this.sSpecial3Id = aSpecial3Id;
	}


	public int getId() {
		return sId;
	}

	public int getOwnerId() {
		return sOwnerId;
	}

	public java.lang.String getName() {
		return sName;
	}

	public byte getChasis() {
		return sChasis;
	}

	public short getWeapon1Id() {
		return sWeapon1Id;
	}

	public short getWeapon2Id() {
		return sWeapon2Id;
	}

	public short getWeapon3Id() {
		return sWeapon3Id;
	}

	public short getArmor1Id() {
		return sArmor1Id;
	}

	public short getArmor2Id() {
		return sArmor2Id;
	}

	public short getArmor3Id() {
		return sArmor3Id;
	}

	public short getSpecial1Id() {
		return sSpecial1Id;
	}

	public short getSpecial2Id() {
		return sSpecial2Id;
	}

	public short getSpecial3Id() {
		return sSpecial3Id;
	}
}

