package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACDesignsTable extends ACDesignsList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACDesignsTable() {
	} 

	public void remove(ACDesigns aACDesigns) {
		aACDesigns.setSQLaction(3);
		appendSQLsync(aACDesigns);
		this.ACDesignsVector.remove(aACDesigns);
	}

	public ACDesigns create() {
		max_id++;
		ACDesigns aACDesigns = new ACDesigns(max_id);
		ACDesignsVector.add(aACDesigns); //bypass sort algorithm
		return aACDesigns;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACDesigns current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACDesigns)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACDesigns aACDesigns) {
		SQLsyncObjects.push(aACDesigns);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, owner_id, name, chasis, weapon1_id, weapon2_id, weapon3_id, armor1_id, armor2_id, armor3_id, special1_id, special2_id, special3_id FROM designs ORDER BY id");
			ACDesigns loadedSQLACDesigns;
			while (res.next()) {
				loadedSQLACDesigns = new ACDesigns(res);
				ACDesignsVector.add(loadedSQLACDesigns); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

