package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACEventsTable extends ACEventsList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACEventsTable() {
	} 

	public void remove(ACEvents aACEvents) {
		aACEvents.setSQLaction(3);
		appendSQLsync(aACEvents);
		this.ACEventsVector.remove(aACEvents);
	}

	public ACEvents create() {
		max_id++;
		ACEvents aACEvents = new ACEvents(max_id);
		ACEventsVector.add(aACEvents); //bypass sort algorithm
		return aACEvents;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACEvents current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACEvents)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACEvents aACEvents) {
		SQLsyncObjects.push(aACEvents);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, event_id, owner_id, start_time FROM events ORDER BY id");
			ACEvents loadedSQLACEvents;
			while (res.next()) {
				loadedSQLACEvents = new ACEvents(res);
				ACEventsVector.add(loadedSQLACEvents); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

