package org.archcave.classes;
import java.util.Vector;
import org.archcave.libs.JHash;

//List generated by zbyte's sql to java script
public class ACInhabitantsList {
	protected Vector ACInhabitantsVector = new Vector();
	
	public void add(ACInhabitants aACInhabitants) {
		if (ACInhabitantsVector.size() == 0) {
			ACInhabitantsVector.add(0, aACInhabitants);
			return;
		}
		int middle = (ACInhabitantsVector.size()-1)/2;
		int index = middle;
		ACInhabitants current = (ACInhabitants)ACInhabitantsVector.get(index);
		while ((index > 0)&&(current.getId() > aACInhabitants.getId()))
		{
			index--;
			current = (ACInhabitants)ACInhabitantsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACInhabitantsVector.size() - 1 )&&(current.getId() < aACInhabitants.getId()))
			{
				index++;
				current = (ACInhabitants)ACInhabitantsVector.get(index);
			}
		}
		ACInhabitantsVector.add(index, aACInhabitants);
	}
	
	public ACInhabitants fetch(int aID) {
		if (ACInhabitantsVector.size() == 0) return null;
		int middle = (ACInhabitantsVector.size()-1)/2;
		int index = middle;
		ACInhabitants current = (ACInhabitants)ACInhabitantsVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACInhabitants)ACInhabitantsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACInhabitantsVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACInhabitants)ACInhabitantsVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACInhabitantsVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACInhabitants aACInhabitants) {//done
		this.ACInhabitantsVector.remove(aACInhabitants);
	}
	
	public int length() {//done
		return this.ACInhabitantsVector.size();
	}
	
	public ACInhabitants get(int aNumber) {//done
		return (ACInhabitants)ACInhabitantsVector.get(aNumber);
	}

	public ACInhabitantsList findByTerritoryId(int aTerritoryId) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aTerritoryId == current.getTerritoryId()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByOwnerId(int aOwnerId) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByOldOwnerId(int aOldOwnerId) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aOldOwnerId == current.getOldOwnerId()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByLoyalty(byte aLoyalty) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aLoyalty == current.getLoyalty()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByName(java.lang.String aName) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aName.equals(current.getName())) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByPopulation(short aPopulation) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aPopulation == current.getPopulation()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByGrain(short aGrain) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aGrain == current.getGrain()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByProductionPoints(short aProductionPoints) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aProductionPoints == current.getProductionPoints()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByDomesticProductionId(short aDomesticProductionId) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aDomesticProductionId == current.getDomesticProductionId()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByMilitaryProductionId(short aMilitaryProductionId) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aMilitaryProductionId == current.getMilitaryProductionId()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByGovernorCanBuildUnits(byte aGovernorCanBuildUnits) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aGovernorCanBuildUnits == current.getGovernorCanBuildUnits()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByInvestment(int aInvestment) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aInvestment == current.getInvestment()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByVitality(byte aVitality) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aVitality == current.getVitality()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}

	public ACInhabitantsList findByImprovementsHash(org.archcave.libs.JHash aImprovementsHash) {
		ACInhabitantsList aACInhabitantsList = new ACInhabitantsList();
		ACInhabitants current;
		for (int i = 0; i < this.ACInhabitantsVector.size(); i++) {
			current = (ACInhabitants)this.ACInhabitantsVector.get(i);
			if (aImprovementsHash == current.getImprovementsHash()) {
				aACInhabitantsList.add(current);
			}
		}
		return aACInhabitantsList;
	}
}

