package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Object generated by zbyte's sql to java script
public class ACInhabitants {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sTerritoryId;
	private int sOwnerId;
	private int sOldOwnerId;
	private byte sLoyalty;
	private java.lang.String sName;
	private short sPopulation;
	private short sGrain;
	private short sProductionPoints;
	private short sDomesticProductionId;
	private short sMilitaryProductionId;
	private byte sGovernorCanBuildUnits;
	private int sInvestment;
	private byte sVitality;
	private org.archcave.libs.JHash sImprovementsHash;

	public static ACInhabitantsTable mTable;
	public static final short E_ID=0;
	public static final short E_TERRITORYID=1;
	public static final short E_OWNERID=2;
	public static final short E_OLDOWNERID=3;
	public static final short E_LOYALTY=4;
	public static final short E_NAME=5;
	public static final short E_POPULATION=6;
	public static final short E_GRAIN=7;
	public static final short E_PRODUCTIONPOINTS=8;
	public static final short E_DOMESTICPRODUCTIONID=9;
	public static final short E_MILITARYPRODUCTIONID=10;
	public static final short E_GOVERNORCANBUILDUNITS=11;
	public static final short E_INVESTMENT=12;
	public static final short E_VITALITY=13;
	public static final short E_IMPROVEMENTSHASH=14;

	public ACInhabitants(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACInhabitants(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sTerritoryId = (int)Integer.parseInt(SQLRes.getObject(E_TERRITORYID).toString());
			sOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OWNERID).toString());
			sOldOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OLDOWNERID).toString());
			sLoyalty = (byte)Integer.parseInt(SQLRes.getObject(E_LOYALTY).toString());
			sName = SQLRes.getObject(E_NAME).toString();
			sPopulation = (short)Integer.parseInt(SQLRes.getObject(E_POPULATION).toString());
			sGrain = (short)Integer.parseInt(SQLRes.getObject(E_GRAIN).toString());
			sProductionPoints = (short)Integer.parseInt(SQLRes.getObject(E_PRODUCTIONPOINTS).toString());
			sDomesticProductionId = (short)Integer.parseInt(SQLRes.getObject(E_DOMESTICPRODUCTIONID).toString());
			sMilitaryProductionId = (short)Integer.parseInt(SQLRes.getObject(E_MILITARYPRODUCTIONID).toString());
			sGovernorCanBuildUnits = (byte)Integer.parseInt(SQLRes.getObject(E_GOVERNORCANBUILDUNITS).toString());
			sInvestment = (int)Integer.parseInt(SQLRes.getObject(E_INVESTMENT).toString());
			sVitality = (byte)Integer.parseInt(SQLRes.getObject(E_VITALITY).toString());
			sImprovementsHash = new JHash(SQLRes.getObject(E_IMPROVEMENTSHASH).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_TERRITORYID)) result += " territory_id="+sTerritoryId + ",";
		if (mStoreFlags.get(E_OWNERID)) result += " owner_id="+sOwnerId + ",";
		if (mStoreFlags.get(E_OLDOWNERID)) result += " old_owner_id="+sOldOwnerId + ",";
		if (mStoreFlags.get(E_LOYALTY)) result += " loyalty="+sLoyalty + ",";
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_POPULATION)) result += " population="+sPopulation + ",";
		if (mStoreFlags.get(E_GRAIN)) result += " grain="+sGrain + ",";
		if (mStoreFlags.get(E_PRODUCTIONPOINTS)) result += " production_points="+sProductionPoints + ",";
		if (mStoreFlags.get(E_DOMESTICPRODUCTIONID)) result += " domestic_production_id="+sDomesticProductionId + ",";
		if (mStoreFlags.get(E_MILITARYPRODUCTIONID)) result += " military_production_id="+sMilitaryProductionId + ",";
		if (mStoreFlags.get(E_GOVERNORCANBUILDUNITS)) result += " governor_can_build_units="+sGovernorCanBuildUnits + ",";
		if (mStoreFlags.get(E_INVESTMENT)) result += " investment="+sInvestment + ",";
		if (mStoreFlags.get(E_VITALITY)) result += " vitality="+sVitality + ",";
		if (mStoreFlags.get(E_IMPROVEMENTSHASH)) result += " improvements_hash="+sImprovementsHash + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_TERRITORYID)) { vars += "territory_id,"; values += sTerritoryId + ",";}
		if (mStoreFlags.get(E_OWNERID)) { vars += "owner_id,"; values += sOwnerId + ",";}
		if (mStoreFlags.get(E_OLDOWNERID)) { vars += "old_owner_id,"; values += sOldOwnerId + ",";}
		if (mStoreFlags.get(E_LOYALTY)) { vars += "loyalty,"; values += sLoyalty + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_POPULATION)) { vars += "population,"; values += sPopulation + ",";}
		if (mStoreFlags.get(E_GRAIN)) { vars += "grain,"; values += sGrain + ",";}
		if (mStoreFlags.get(E_PRODUCTIONPOINTS)) { vars += "production_points,"; values += sProductionPoints + ",";}
		if (mStoreFlags.get(E_DOMESTICPRODUCTIONID)) { vars += "domestic_production_id,"; values += sDomesticProductionId + ",";}
		if (mStoreFlags.get(E_MILITARYPRODUCTIONID)) { vars += "military_production_id,"; values += sMilitaryProductionId + ",";}
		if (mStoreFlags.get(E_GOVERNORCANBUILDUNITS)) { vars += "governor_can_build_units,"; values += sGovernorCanBuildUnits + ",";}
		if (mStoreFlags.get(E_INVESTMENT)) { vars += "investment,"; values += sInvestment + ",";}
		if (mStoreFlags.get(E_VITALITY)) { vars += "vitality,"; values += sVitality + ",";}
		if (mStoreFlags.get(E_IMPROVEMENTSHASH)) { vars += "improvements_hash,"; values += sImprovementsHash + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO inhabitants "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE inhabitants SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM inhabitants WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setTerritoryId(int aTerritoryId) {
		this.mStoreFlags.set(E_TERRITORYID);
		this.setSQLaction(2);
		this.sTerritoryId = aTerritoryId;
	}

	public void setOwnerId(int aOwnerId) {
		this.mStoreFlags.set(E_OWNERID);
		this.setSQLaction(2);
		this.sOwnerId = aOwnerId;
	}

	public void setOldOwnerId(int aOldOwnerId) {
		this.mStoreFlags.set(E_OLDOWNERID);
		this.setSQLaction(2);
		this.sOldOwnerId = aOldOwnerId;
	}

	public void setLoyalty(byte aLoyalty) {
		this.mStoreFlags.set(E_LOYALTY);
		this.setSQLaction(2);
		this.sLoyalty = aLoyalty;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setPopulation(short aPopulation) {
		this.mStoreFlags.set(E_POPULATION);
		this.setSQLaction(2);
		this.sPopulation = aPopulation;
	}

	public void setGrain(short aGrain) {
		this.mStoreFlags.set(E_GRAIN);
		this.setSQLaction(2);
		this.sGrain = aGrain;
	}

	public void setProductionPoints(short aProductionPoints) {
		this.mStoreFlags.set(E_PRODUCTIONPOINTS);
		this.setSQLaction(2);
		this.sProductionPoints = aProductionPoints;
	}

	public void setDomesticProductionId(short aDomesticProductionId) {
		this.mStoreFlags.set(E_DOMESTICPRODUCTIONID);
		this.setSQLaction(2);
		this.sDomesticProductionId = aDomesticProductionId;
	}

	public void setMilitaryProductionId(short aMilitaryProductionId) {
		this.mStoreFlags.set(E_MILITARYPRODUCTIONID);
		this.setSQLaction(2);
		this.sMilitaryProductionId = aMilitaryProductionId;
	}

	public void setGovernorCanBuildUnits(byte aGovernorCanBuildUnits) {
		this.mStoreFlags.set(E_GOVERNORCANBUILDUNITS);
		this.setSQLaction(2);
		this.sGovernorCanBuildUnits = aGovernorCanBuildUnits;
	}

	public void setInvestment(int aInvestment) {
		this.mStoreFlags.set(E_INVESTMENT);
		this.setSQLaction(2);
		this.sInvestment = aInvestment;
	}

	public void setVitality(byte aVitality) {
		this.mStoreFlags.set(E_VITALITY);
		this.setSQLaction(2);
		this.sVitality = aVitality;
	}

	public void setImprovementsHash(org.archcave.libs.JHash aImprovementsHash) {
		this.mStoreFlags.set(E_IMPROVEMENTSHASH);
		this.setSQLaction(2);
		this.sImprovementsHash = aImprovementsHash;
	}


	public int getId() {
		return sId;
	}

	public int getTerritoryId() {
		return sTerritoryId;
	}

	public int getOwnerId() {
		return sOwnerId;
	}

	public int getOldOwnerId() {
		return sOldOwnerId;
	}

	public byte getLoyalty() {
		return sLoyalty;
	}

	public java.lang.String getName() {
		return sName;
	}

	public short getPopulation() {
		return sPopulation;
	}

	public short getGrain() {
		return sGrain;
	}

	public short getProductionPoints() {
		return sProductionPoints;
	}

	public short getDomesticProductionId() {
		return sDomesticProductionId;
	}

	public short getMilitaryProductionId() {
		return sMilitaryProductionId;
	}

	public byte getGovernorCanBuildUnits() {
		return sGovernorCanBuildUnits;
	}

	public int getInvestment() {
		return sInvestment;
	}

	public byte getVitality() {
		return sVitality;
	}

	public org.archcave.libs.JHash getImprovementsHash() {
		return sImprovementsHash;
	}
}

