package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Table generated by zbyte's sql to java script
public class ACInhabitantsTable extends ACInhabitantsList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACInhabitantsTable() {
	} 

	public void remove(ACInhabitants aACInhabitants) {
		aACInhabitants.setSQLaction(3);
		appendSQLsync(aACInhabitants);
		this.ACInhabitantsVector.remove(aACInhabitants);
	}

	public ACInhabitants create() {
		max_id++;
		ACInhabitants aACInhabitants = new ACInhabitants(max_id);
		ACInhabitantsVector.add(aACInhabitants); //bypass sort algorithm
		return aACInhabitants;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACInhabitants current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACInhabitants)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACInhabitants aACInhabitants) {
		SQLsyncObjects.push(aACInhabitants);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, territory_id, owner_id, old_owner_id, loyalty, name, population, grain, production_points, domestic_production_id, military_production_id, governor_can_build_units, investment, vitality, improvements_hash FROM inhabitants ORDER BY id");
			ACInhabitants loadedSQLACInhabitants;
			while (res.next()) {
				loadedSQLACInhabitants = new ACInhabitants(res);
				ACInhabitantsVector.add(loadedSQLACInhabitants); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

