package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACMessagesList {
	protected Vector ACMessagesVector = new Vector();
	
	public void add(ACMessages aACMessages) {
		if (ACMessagesVector.size() == 0) {
			ACMessagesVector.add(0, aACMessages);
			return;
		}
		int middle = (ACMessagesVector.size()-1)/2;
		int index = middle;
		ACMessages current = (ACMessages)ACMessagesVector.get(index);
		while ((index > 0)&&(current.getId() > aACMessages.getId()))
		{
			index--;
			current = (ACMessages)ACMessagesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACMessagesVector.size() - 1 )&&(current.getId() < aACMessages.getId()))
			{
				index++;
				current = (ACMessages)ACMessagesVector.get(index);
			}
		}
		ACMessagesVector.add(index, aACMessages);
	}
	
	public ACMessages fetch(int aID) {
		if (ACMessagesVector.size() == 0) return null;
		int middle = (ACMessagesVector.size()-1)/2;
		int index = middle;
		ACMessages current = (ACMessages)ACMessagesVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACMessages)ACMessagesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACMessagesVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACMessages)ACMessagesVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACMessagesVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACMessages aACMessages) {//done
		this.ACMessagesVector.remove(aACMessages);
	}
	
	public int length() {//done
		return this.ACMessagesVector.size();
	}
	
	public ACMessages get(int aNumber) {//done
		return (ACMessages)ACMessagesVector.get(aNumber);
	}

	public ACMessagesList findBySenderId(int aSenderId) {
		ACMessagesList aACMessagesList = new ACMessagesList();
		ACMessages current;
		for (int i = 0; i < this.ACMessagesVector.size(); i++) {
			current = (ACMessages)this.ACMessagesVector.get(i);
			if (aSenderId == current.getSenderId()) {
				aACMessagesList.add(current);
			}
		}
		return aACMessagesList;
	}

	public ACMessagesList findByRecieverId(int aRecieverId) {
		ACMessagesList aACMessagesList = new ACMessagesList();
		ACMessages current;
		for (int i = 0; i < this.ACMessagesVector.size(); i++) {
			current = (ACMessages)this.ACMessagesVector.get(i);
			if (aRecieverId == current.getRecieverId()) {
				aACMessagesList.add(current);
			}
		}
		return aACMessagesList;
	}

	public ACMessagesList findByType(byte aType) {
		ACMessagesList aACMessagesList = new ACMessagesList();
		ACMessages current;
		for (int i = 0; i < this.ACMessagesVector.size(); i++) {
			current = (ACMessages)this.ACMessagesVector.get(i);
			if (aType == current.getType()) {
				aACMessagesList.add(current);
			}
		}
		return aACMessagesList;
	}

	public ACMessagesList findByContent(int aContent) {
		ACMessagesList aACMessagesList = new ACMessagesList();
		ACMessages current;
		for (int i = 0; i < this.ACMessagesVector.size(); i++) {
			current = (ACMessages)this.ACMessagesVector.get(i);
			if (aContent == current.getContent()) {
				aACMessagesList.add(current);
			}
		}
		return aACMessagesList;
	}
}

