package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACPlayerActionTable extends ACPlayerActionList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACPlayerActionTable() {
	} 

	public void remove(ACPlayerAction aACPlayerAction) {
		aACPlayerAction.setSQLaction(3);
		appendSQLsync(aACPlayerAction);
		this.ACPlayerActionVector.remove(aACPlayerAction);
	}

	public ACPlayerAction create() {
		max_id++;
		ACPlayerAction aACPlayerAction = new ACPlayerAction(max_id);
		ACPlayerActionVector.add(aACPlayerAction); //bypass sort algorithm
		return aACPlayerAction;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACPlayerAction current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACPlayerAction)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACPlayerAction aACPlayerAction) {
		SQLsyncObjects.push(aACPlayerAction);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, type, owner_id FROM playerAction ORDER BY id");
			ACPlayerAction loadedSQLACPlayerAction;
			while (res.next()) {
				loadedSQLACPlayerAction = new ACPlayerAction(res);
				ACPlayerActionVector.add(loadedSQLACPlayerAction); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

