package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Object generated by zbyte's sql to java script
public class ACPlayers {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private java.lang.String sName;
	private int sRulerId;
	private org.archcave.libs.JHash sChoicesHash;
	private org.archcave.libs.JHash sPoliciesHash;
	private org.archcave.libs.JHash sTechHash;
	private org.archcave.libs.JHash sAbilitiesHash;
	private byte sEra;
	private long sCurrency;
	private int sResearchInvest;
	private short sCurrentResearchId;
	private int sResearchPoints;
	private byte sHonor;
	private byte sSecurityLevel;
	private byte sAlertness;
	private int sTurn;
	private int sNewsTurn;
	private int sNewsProduction;
	private int sNewsResearch;
	private int sNewsPopulation;

	public static ACPlayersTable mTable;
	public static final short E_ID=0;
	public static final short E_NAME=1;
	public static final short E_RULERID=2;
	public static final short E_CHOICESHASH=3;
	public static final short E_POLICIESHASH=4;
	public static final short E_TECHHASH=5;
	public static final short E_ABILITIESHASH=6;
	public static final short E_ERA=7;
	public static final short E_CURRENCY=8;
	public static final short E_RESEARCHINVEST=9;
	public static final short E_CURRENTRESEARCHID=10;
	public static final short E_RESEARCHPOINTS=11;
	public static final short E_HONOR=12;
	public static final short E_SECURITYLEVEL=13;
	public static final short E_ALERTNESS=14;
	public static final short E_TURN=15;
	public static final short E_NEWSTURN=16;
	public static final short E_NEWSPRODUCTION=17;
	public static final short E_NEWSRESEARCH=18;
	public static final short E_NEWSPOPULATION=19;

	public ACPlayers(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACPlayers(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sName = SQLRes.getObject(E_NAME).toString();
			sRulerId = (int)Integer.parseInt(SQLRes.getObject(E_RULERID).toString());
			sChoicesHash = new JHash(SQLRes.getObject(E_CHOICESHASH).toString());
			sPoliciesHash = new JHash(SQLRes.getObject(E_POLICIESHASH).toString());
			sTechHash = new JHash(SQLRes.getObject(E_TECHHASH).toString());
			sAbilitiesHash = new JHash(SQLRes.getObject(E_ABILITIESHASH).toString());
			sEra = (byte)Integer.parseInt(SQLRes.getObject(E_ERA).toString());
			sCurrency = (long)Integer.parseInt(SQLRes.getObject(E_CURRENCY).toString());
			sResearchInvest = (int)Integer.parseInt(SQLRes.getObject(E_RESEARCHINVEST).toString());
			sCurrentResearchId = (short)Integer.parseInt(SQLRes.getObject(E_CURRENTRESEARCHID).toString());
			sResearchPoints = (int)Integer.parseInt(SQLRes.getObject(E_RESEARCHPOINTS).toString());
			sHonor = (byte)Integer.parseInt(SQLRes.getObject(E_HONOR).toString());
			sSecurityLevel = (byte)Integer.parseInt(SQLRes.getObject(E_SECURITYLEVEL).toString());
			sAlertness = (byte)Integer.parseInt(SQLRes.getObject(E_ALERTNESS).toString());
			sTurn = (int)Integer.parseInt(SQLRes.getObject(E_TURN).toString());
			sNewsTurn = (int)Integer.parseInt(SQLRes.getObject(E_NEWSTURN).toString());
			sNewsProduction = (int)Integer.parseInt(SQLRes.getObject(E_NEWSPRODUCTION).toString());
			sNewsResearch = (int)Integer.parseInt(SQLRes.getObject(E_NEWSRESEARCH).toString());
			sNewsPopulation = (int)Integer.parseInt(SQLRes.getObject(E_NEWSPOPULATION).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_RULERID)) result += " ruler_id="+sRulerId + ",";
		if (mStoreFlags.get(E_CHOICESHASH)) result += " choices_hash="+sChoicesHash + ",";
		if (mStoreFlags.get(E_POLICIESHASH)) result += " policies_hash="+sPoliciesHash + ",";
		if (mStoreFlags.get(E_TECHHASH)) result += " tech_hash="+sTechHash + ",";
		if (mStoreFlags.get(E_ABILITIESHASH)) result += " abilities_hash="+sAbilitiesHash + ",";
		if (mStoreFlags.get(E_ERA)) result += " era="+sEra + ",";
		if (mStoreFlags.get(E_CURRENCY)) result += " currency="+sCurrency + ",";
		if (mStoreFlags.get(E_RESEARCHINVEST)) result += " research_invest="+sResearchInvest + ",";
		if (mStoreFlags.get(E_CURRENTRESEARCHID)) result += " current_research_id="+sCurrentResearchId + ",";
		if (mStoreFlags.get(E_RESEARCHPOINTS)) result += " research_points="+sResearchPoints + ",";
		if (mStoreFlags.get(E_HONOR)) result += " honor="+sHonor + ",";
		if (mStoreFlags.get(E_SECURITYLEVEL)) result += " security_level="+sSecurityLevel + ",";
		if (mStoreFlags.get(E_ALERTNESS)) result += " alertness="+sAlertness + ",";
		if (mStoreFlags.get(E_TURN)) result += " turn="+sTurn + ",";
		if (mStoreFlags.get(E_NEWSTURN)) result += " news_turn="+sNewsTurn + ",";
		if (mStoreFlags.get(E_NEWSPRODUCTION)) result += " news_production="+sNewsProduction + ",";
		if (mStoreFlags.get(E_NEWSRESEARCH)) result += " news_research="+sNewsResearch + ",";
		if (mStoreFlags.get(E_NEWSPOPULATION)) result += " news_population="+sNewsPopulation + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_RULERID)) { vars += "ruler_id,"; values += sRulerId + ",";}
		if (mStoreFlags.get(E_CHOICESHASH)) { vars += "choices_hash,"; values += sChoicesHash + ",";}
		if (mStoreFlags.get(E_POLICIESHASH)) { vars += "policies_hash,"; values += sPoliciesHash + ",";}
		if (mStoreFlags.get(E_TECHHASH)) { vars += "tech_hash,"; values += sTechHash + ",";}
		if (mStoreFlags.get(E_ABILITIESHASH)) { vars += "abilities_hash,"; values += sAbilitiesHash + ",";}
		if (mStoreFlags.get(E_ERA)) { vars += "era,"; values += sEra + ",";}
		if (mStoreFlags.get(E_CURRENCY)) { vars += "currency,"; values += sCurrency + ",";}
		if (mStoreFlags.get(E_RESEARCHINVEST)) { vars += "research_invest,"; values += sResearchInvest + ",";}
		if (mStoreFlags.get(E_CURRENTRESEARCHID)) { vars += "current_research_id,"; values += sCurrentResearchId + ",";}
		if (mStoreFlags.get(E_RESEARCHPOINTS)) { vars += "research_points,"; values += sResearchPoints + ",";}
		if (mStoreFlags.get(E_HONOR)) { vars += "honor,"; values += sHonor + ",";}
		if (mStoreFlags.get(E_SECURITYLEVEL)) { vars += "security_level,"; values += sSecurityLevel + ",";}
		if (mStoreFlags.get(E_ALERTNESS)) { vars += "alertness,"; values += sAlertness + ",";}
		if (mStoreFlags.get(E_TURN)) { vars += "turn,"; values += sTurn + ",";}
		if (mStoreFlags.get(E_NEWSTURN)) { vars += "news_turn,"; values += sNewsTurn + ",";}
		if (mStoreFlags.get(E_NEWSPRODUCTION)) { vars += "news_production,"; values += sNewsProduction + ",";}
		if (mStoreFlags.get(E_NEWSRESEARCH)) { vars += "news_research,"; values += sNewsResearch + ",";}
		if (mStoreFlags.get(E_NEWSPOPULATION)) { vars += "news_population,"; values += sNewsPopulation + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO players "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE players SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM players WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setRulerId(int aRulerId) {
		this.mStoreFlags.set(E_RULERID);
		this.setSQLaction(2);
		this.sRulerId = aRulerId;
	}

	public void setChoicesHash(org.archcave.libs.JHash aChoicesHash) {
		this.mStoreFlags.set(E_CHOICESHASH);
		this.setSQLaction(2);
		this.sChoicesHash = aChoicesHash;
	}

	public void setPoliciesHash(org.archcave.libs.JHash aPoliciesHash) {
		this.mStoreFlags.set(E_POLICIESHASH);
		this.setSQLaction(2);
		this.sPoliciesHash = aPoliciesHash;
	}

	public void setTechHash(org.archcave.libs.JHash aTechHash) {
		this.mStoreFlags.set(E_TECHHASH);
		this.setSQLaction(2);
		this.sTechHash = aTechHash;
	}

	public void setAbilitiesHash(org.archcave.libs.JHash aAbilitiesHash) {
		this.mStoreFlags.set(E_ABILITIESHASH);
		this.setSQLaction(2);
		this.sAbilitiesHash = aAbilitiesHash;
	}

	public void setEra(byte aEra) {
		this.mStoreFlags.set(E_ERA);
		this.setSQLaction(2);
		this.sEra = aEra;
	}

	public void setCurrency(long aCurrency) {
		this.mStoreFlags.set(E_CURRENCY);
		this.setSQLaction(2);
		this.sCurrency = aCurrency;
	}

	public void setResearchInvest(int aResearchInvest) {
		this.mStoreFlags.set(E_RESEARCHINVEST);
		this.setSQLaction(2);
		this.sResearchInvest = aResearchInvest;
	}

	public void setCurrentResearchId(short aCurrentResearchId) {
		this.mStoreFlags.set(E_CURRENTRESEARCHID);
		this.setSQLaction(2);
		this.sCurrentResearchId = aCurrentResearchId;
	}

	public void setResearchPoints(int aResearchPoints) {
		this.mStoreFlags.set(E_RESEARCHPOINTS);
		this.setSQLaction(2);
		this.sResearchPoints = aResearchPoints;
	}

	public void setHonor(byte aHonor) {
		this.mStoreFlags.set(E_HONOR);
		this.setSQLaction(2);
		this.sHonor = aHonor;
	}

	public void setSecurityLevel(byte aSecurityLevel) {
		this.mStoreFlags.set(E_SECURITYLEVEL);
		this.setSQLaction(2);
		this.sSecurityLevel = aSecurityLevel;
	}

	public void setAlertness(byte aAlertness) {
		this.mStoreFlags.set(E_ALERTNESS);
		this.setSQLaction(2);
		this.sAlertness = aAlertness;
	}

	public void setTurn(int aTurn) {
		this.mStoreFlags.set(E_TURN);
		this.setSQLaction(2);
		this.sTurn = aTurn;
	}

	public void setNewsTurn(int aNewsTurn) {
		this.mStoreFlags.set(E_NEWSTURN);
		this.setSQLaction(2);
		this.sNewsTurn = aNewsTurn;
	}

	public void setNewsProduction(int aNewsProduction) {
		this.mStoreFlags.set(E_NEWSPRODUCTION);
		this.setSQLaction(2);
		this.sNewsProduction = aNewsProduction;
	}

	public void setNewsResearch(int aNewsResearch) {
		this.mStoreFlags.set(E_NEWSRESEARCH);
		this.setSQLaction(2);
		this.sNewsResearch = aNewsResearch;
	}

	public void setNewsPopulation(int aNewsPopulation) {
		this.mStoreFlags.set(E_NEWSPOPULATION);
		this.setSQLaction(2);
		this.sNewsPopulation = aNewsPopulation;
	}


	public int getId() {
		return sId;
	}

	public java.lang.String getName() {
		return sName;
	}

	public int getRulerId() {
		return sRulerId;
	}

	public org.archcave.libs.JHash getChoicesHash() {
		return sChoicesHash;
	}

	public org.archcave.libs.JHash getPoliciesHash() {
		return sPoliciesHash;
	}

	public org.archcave.libs.JHash getTechHash() {
		return sTechHash;
	}

	public org.archcave.libs.JHash getAbilitiesHash() {
		return sAbilitiesHash;
	}

	public byte getEra() {
		return sEra;
	}

	public long getCurrency() {
		return sCurrency;
	}

	public int getResearchInvest() {
		return sResearchInvest;
	}

	public short getCurrentResearchId() {
		return sCurrentResearchId;
	}

	public int getResearchPoints() {
		return sResearchPoints;
	}

	public byte getHonor() {
		return sHonor;
	}

	public byte getSecurityLevel() {
		return sSecurityLevel;
	}

	public byte getAlertness() {
		return sAlertness;
	}

	public int getTurn() {
		return sTurn;
	}

	public int getNewsTurn() {
		return sNewsTurn;
	}

	public int getNewsProduction() {
		return sNewsProduction;
	}

	public int getNewsResearch() {
		return sNewsResearch;
	}

	public int getNewsPopulation() {
		return sNewsPopulation;
	}
}

