package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACPlayerActionList {
	protected Vector ACPlayerActionVector = new Vector();
	
	public void add(ACPlayerAction aACPlayerAction) {
		if (ACPlayerActionVector.size() == 0) {
			ACPlayerActionVector.add(0, aACPlayerAction);
			return;
		}
		int middle = (ACPlayerActionVector.size()-1)/2;
		int index = middle;
		ACPlayerAction current = (ACPlayerAction)ACPlayerActionVector.get(index);
		while ((index > 0)&&(current.getId() > aACPlayerAction.getId()))
		{
			index--;
			current = (ACPlayerAction)ACPlayerActionVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACPlayerActionVector.size() - 1 )&&(current.getId() < aACPlayerAction.getId()))
			{
				index++;
				current = (ACPlayerAction)ACPlayerActionVector.get(index);
			}
		}
		ACPlayerActionVector.add(index, aACPlayerAction);
	}
	
	public ACPlayerAction fetch(int aID) {
		if (ACPlayerActionVector.size() == 0) return null;
		int middle = (ACPlayerActionVector.size()-1)/2;
		int index = middle;
		ACPlayerAction current = (ACPlayerAction)ACPlayerActionVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACPlayerAction)ACPlayerActionVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACPlayerActionVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACPlayerAction)ACPlayerActionVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACPlayerActionVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACPlayerAction aACPlayerAction) {//done
		this.ACPlayerActionVector.remove(aACPlayerAction);
	}
	
	public int length() {//done
		return this.ACPlayerActionVector.size();
	}
	
	public ACPlayerAction get(int aNumber) {//done
		return (ACPlayerAction)ACPlayerActionVector.get(aNumber);
	}

	public ACPlayerActionList findByType(byte aType) {
		ACPlayerActionList aACPlayerActionList = new ACPlayerActionList();
		ACPlayerAction current;
		for (int i = 0; i < this.ACPlayerActionVector.size(); i++) {
			current = (ACPlayerAction)this.ACPlayerActionVector.get(i);
			if (aType == current.getType()) {
				aACPlayerActionList.add(current);
			}
		}
		return aACPlayerActionList;
	}

	public ACPlayerActionList findByOwnerId(int aOwnerId) {
		ACPlayerActionList aACPlayerActionList = new ACPlayerActionList();
		ACPlayerAction current;
		for (int i = 0; i < this.ACPlayerActionVector.size(); i++) {
			current = (ACPlayerAction)this.ACPlayerActionVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACPlayerActionList.add(current);
			}
		}
		return aACPlayerActionList;
	}
}

