package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACRelations {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sPlayer1Id;
	private int sPlayer2Id;
	private byte sType;

	public static ACRelationsTable mTable;
	public static final short E_ID=0;
	public static final short E_PLAYER1ID=1;
	public static final short E_PLAYER2ID=2;
	public static final short E_TYPE=3;

	public ACRelations(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACRelations(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sPlayer1Id = (int)Integer.parseInt(SQLRes.getObject(E_PLAYER1ID).toString());
			sPlayer2Id = (int)Integer.parseInt(SQLRes.getObject(E_PLAYER2ID).toString());
			sType = (byte)Integer.parseInt(SQLRes.getObject(E_TYPE).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_PLAYER1ID)) result += " player1_id="+sPlayer1Id + ",";
		if (mStoreFlags.get(E_PLAYER2ID)) result += " player2_id="+sPlayer2Id + ",";
		if (mStoreFlags.get(E_TYPE)) result += " type="+sType + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_PLAYER1ID)) { vars += "player1_id,"; values += sPlayer1Id + ",";}
		if (mStoreFlags.get(E_PLAYER2ID)) { vars += "player2_id,"; values += sPlayer2Id + ",";}
		if (mStoreFlags.get(E_TYPE)) { vars += "type,"; values += sType + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO relations "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE relations SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM relations WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setPlayer1Id(int aPlayer1Id) {
		this.mStoreFlags.set(E_PLAYER1ID);
		this.setSQLaction(2);
		this.sPlayer1Id = aPlayer1Id;
	}

	public void setPlayer2Id(int aPlayer2Id) {
		this.mStoreFlags.set(E_PLAYER2ID);
		this.setSQLaction(2);
		this.sPlayer2Id = aPlayer2Id;
	}

	public void setType(byte aType) {
		this.mStoreFlags.set(E_TYPE);
		this.setSQLaction(2);
		this.sType = aType;
	}


	public int getId() {
		return sId;
	}

	public int getPlayer1Id() {
		return sPlayer1Id;
	}

	public int getPlayer2Id() {
		return sPlayer2Id;
	}

	public byte getType() {
		return sType;
	}
}

