package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACSquads {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sArmyId;
	private java.lang.String sName;
	private int sDesignId;
	private byte sQuantity;
	private byte sVitality;
	private int sHp;
	private int sCommanderId;
	private byte sExperience;
	private byte sMoves;

	public static ACSquadsTable mTable;
	public static final short E_ID=0;
	public static final short E_ARMYID=1;
	public static final short E_NAME=2;
	public static final short E_DESIGNID=3;
	public static final short E_QUANTITY=4;
	public static final short E_VITALITY=5;
	public static final short E_HP=6;
	public static final short E_COMMANDERID=7;
	public static final short E_EXPERIENCE=8;
	public static final short E_MOVES=9;

	public ACSquads(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACSquads(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sArmyId = (int)Integer.parseInt(SQLRes.getObject(E_ARMYID).toString());
			sName = SQLRes.getObject(E_NAME).toString();
			sDesignId = (int)Integer.parseInt(SQLRes.getObject(E_DESIGNID).toString());
			sQuantity = (byte)Integer.parseInt(SQLRes.getObject(E_QUANTITY).toString());
			sVitality = (byte)Integer.parseInt(SQLRes.getObject(E_VITALITY).toString());
			sHp = (int)Integer.parseInt(SQLRes.getObject(E_HP).toString());
			sCommanderId = (int)Integer.parseInt(SQLRes.getObject(E_COMMANDERID).toString());
			sExperience = (byte)Integer.parseInt(SQLRes.getObject(E_EXPERIENCE).toString());
			sMoves = (byte)Integer.parseInt(SQLRes.getObject(E_MOVES).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_ARMYID)) result += " army_id="+sArmyId + ",";
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_DESIGNID)) result += " design_id="+sDesignId + ",";
		if (mStoreFlags.get(E_QUANTITY)) result += " quantity="+sQuantity + ",";
		if (mStoreFlags.get(E_VITALITY)) result += " vitality="+sVitality + ",";
		if (mStoreFlags.get(E_HP)) result += " hp="+sHp + ",";
		if (mStoreFlags.get(E_COMMANDERID)) result += " commander_id="+sCommanderId + ",";
		if (mStoreFlags.get(E_EXPERIENCE)) result += " experience="+sExperience + ",";
		if (mStoreFlags.get(E_MOVES)) result += " moves="+sMoves + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_ARMYID)) { vars += "army_id,"; values += sArmyId + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_DESIGNID)) { vars += "design_id,"; values += sDesignId + ",";}
		if (mStoreFlags.get(E_QUANTITY)) { vars += "quantity,"; values += sQuantity + ",";}
		if (mStoreFlags.get(E_VITALITY)) { vars += "vitality,"; values += sVitality + ",";}
		if (mStoreFlags.get(E_HP)) { vars += "hp,"; values += sHp + ",";}
		if (mStoreFlags.get(E_COMMANDERID)) { vars += "commander_id,"; values += sCommanderId + ",";}
		if (mStoreFlags.get(E_EXPERIENCE)) { vars += "experience,"; values += sExperience + ",";}
		if (mStoreFlags.get(E_MOVES)) { vars += "moves,"; values += sMoves + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO squads "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE squads SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM squads WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setArmyId(int aArmyId) {
		this.mStoreFlags.set(E_ARMYID);
		this.setSQLaction(2);
		this.sArmyId = aArmyId;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setDesignId(int aDesignId) {
		this.mStoreFlags.set(E_DESIGNID);
		this.setSQLaction(2);
		this.sDesignId = aDesignId;
	}

	public void setQuantity(byte aQuantity) {
		this.mStoreFlags.set(E_QUANTITY);
		this.setSQLaction(2);
		this.sQuantity = aQuantity;
	}

	public void setVitality(byte aVitality) {
		this.mStoreFlags.set(E_VITALITY);
		this.setSQLaction(2);
		this.sVitality = aVitality;
	}

	public void setHp(int aHp) {
		this.mStoreFlags.set(E_HP);
		this.setSQLaction(2);
		this.sHp = aHp;
	}

	public void setCommanderId(int aCommanderId) {
		this.mStoreFlags.set(E_COMMANDERID);
		this.setSQLaction(2);
		this.sCommanderId = aCommanderId;
	}

	public void setExperience(byte aExperience) {
		this.mStoreFlags.set(E_EXPERIENCE);
		this.setSQLaction(2);
		this.sExperience = aExperience;
	}

	public void setMoves(byte aMoves) {
		this.mStoreFlags.set(E_MOVES);
		this.setSQLaction(2);
		this.sMoves = aMoves;
	}


	public int getId() {
		return sId;
	}

	public int getArmyId() {
		return sArmyId;
	}

	public java.lang.String getName() {
		return sName;
	}

	public int getDesignId() {
		return sDesignId;
	}

	public byte getQuantity() {
		return sQuantity;
	}

	public byte getVitality() {
		return sVitality;
	}

	public int getHp() {
		return sHp;
	}

	public int getCommanderId() {
		return sCommanderId;
	}

	public byte getExperience() {
		return sExperience;
	}

	public byte getMoves() {
		return sMoves;
	}
}

