package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACSquadsList {
	protected Vector ACSquadsVector = new Vector();
	
	public void add(ACSquads aACSquads) {
		if (ACSquadsVector.size() == 0) {
			ACSquadsVector.add(0, aACSquads);
			return;
		}
		int middle = (ACSquadsVector.size()-1)/2;
		int index = middle;
		ACSquads current = (ACSquads)ACSquadsVector.get(index);
		while ((index > 0)&&(current.getId() > aACSquads.getId()))
		{
			index--;
			current = (ACSquads)ACSquadsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACSquadsVector.size() - 1 )&&(current.getId() < aACSquads.getId()))
			{
				index++;
				current = (ACSquads)ACSquadsVector.get(index);
			}
		}
		ACSquadsVector.add(index, aACSquads);
	}
	
	public ACSquads fetch(int aID) {
		if (ACSquadsVector.size() == 0) return null;
		int middle = (ACSquadsVector.size()-1)/2;
		int index = middle;
		ACSquads current = (ACSquads)ACSquadsVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACSquads)ACSquadsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACSquadsVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACSquads)ACSquadsVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACSquadsVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACSquads aACSquads) {//done
		this.ACSquadsVector.remove(aACSquads);
	}
	
	public int length() {//done
		return this.ACSquadsVector.size();
	}
	
	public ACSquads get(int aNumber) {//done
		return (ACSquads)ACSquadsVector.get(aNumber);
	}

	public ACSquadsList findByArmyId(int aArmyId) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aArmyId == current.getArmyId()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByName(java.lang.String aName) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aName.equals(current.getName())) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByDesignId(int aDesignId) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aDesignId == current.getDesignId()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByQuantity(byte aQuantity) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aQuantity == current.getQuantity()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByVitality(byte aVitality) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aVitality == current.getVitality()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByHp(int aHp) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aHp == current.getHp()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByCommanderId(int aCommanderId) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aCommanderId == current.getCommanderId()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByExperience(byte aExperience) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aExperience == current.getExperience()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}

	public ACSquadsList findByMoves(byte aMoves) {
		ACSquadsList aACSquadsList = new ACSquadsList();
		ACSquads current;
		for (int i = 0; i < this.ACSquadsVector.size(); i++) {
			current = (ACSquads)this.ACSquadsVector.get(i);
			if (aMoves == current.getMoves()) {
				aACSquadsList.add(current);
			}
		}
		return aACSquadsList;
	}
}

