package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACUnitsList {
	protected Vector ACUnitsVector = new Vector();
	
	public void add(ACUnits aACUnits) {
		if (ACUnitsVector.size() == 0) {
			ACUnitsVector.add(0, aACUnits);
			return;
		}
		int middle = (ACUnitsVector.size()-1)/2;
		int index = middle;
		ACUnits current = (ACUnits)ACUnitsVector.get(index);
		while ((index > 0)&&(current.getId() > aACUnits.getId()))
		{
			index--;
			current = (ACUnits)ACUnitsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACUnitsVector.size() - 1 )&&(current.getId() < aACUnits.getId()))
			{
				index++;
				current = (ACUnits)ACUnitsVector.get(index);
			}
		}
		ACUnitsVector.add(index, aACUnits);
	}
	
	public ACUnits fetch(int aID) {
		if (ACUnitsVector.size() == 0) return null;
		int middle = (ACUnitsVector.size()-1)/2;
		int index = middle;
		ACUnits current = (ACUnits)ACUnitsVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACUnits)ACUnitsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACUnitsVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACUnits)ACUnitsVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACUnitsVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACUnits aACUnits) {//done
		this.ACUnitsVector.remove(aACUnits);
	}
	
	public int length() {//done
		return this.ACUnitsVector.size();
	}
	
	public ACUnits get(int aNumber) {//done
		return (ACUnits)ACUnitsVector.get(aNumber);
	}

	public ACUnitsList findByInhabitantId(int aInhabitantId) {
		ACUnitsList aACUnitsList = new ACUnitsList();
		ACUnits current;
		for (int i = 0; i < this.ACUnitsVector.size(); i++) {
			current = (ACUnits)this.ACUnitsVector.get(i);
			if (aInhabitantId == current.getInhabitantId()) {
				aACUnitsList.add(current);
			}
		}
		return aACUnitsList;
	}

	public ACUnitsList findByOwnerId(int aOwnerId) {
		ACUnitsList aACUnitsList = new ACUnitsList();
		ACUnits current;
		for (int i = 0; i < this.ACUnitsVector.size(); i++) {
			current = (ACUnits)this.ACUnitsVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACUnitsList.add(current);
			}
		}
		return aACUnitsList;
	}

	public ACUnitsList findByDesignId(int aDesignId) {
		ACUnitsList aACUnitsList = new ACUnitsList();
		ACUnits current;
		for (int i = 0; i < this.ACUnitsVector.size(); i++) {
			current = (ACUnits)this.ACUnitsVector.get(i);
			if (aDesignId == current.getDesignId()) {
				aACUnitsList.add(current);
			}
		}
		return aACUnitsList;
	}

	public ACUnitsList findByQuantity(byte aQuantity) {
		ACUnitsList aACUnitsList = new ACUnitsList();
		ACUnits current;
		for (int i = 0; i < this.ACUnitsVector.size(); i++) {
			current = (ACUnits)this.ACUnitsVector.get(i);
			if (aQuantity == current.getQuantity()) {
				aACUnitsList.add(current);
			}
		}
		return aACUnitsList;
	}
}

