package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACUnits {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sInhabitantId;
	private int sOwnerId;
	private int sDesignId;
	private byte sQuantity;

	public static ACUnitsTable mTable;
	public static final short E_ID=0;
	public static final short E_INHABITANTID=1;
	public static final short E_OWNERID=2;
	public static final short E_DESIGNID=3;
	public static final short E_QUANTITY=4;

	public ACUnits(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACUnits(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sInhabitantId = (int)Integer.parseInt(SQLRes.getObject(E_INHABITANTID).toString());
			sOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OWNERID).toString());
			sDesignId = (int)Integer.parseInt(SQLRes.getObject(E_DESIGNID).toString());
			sQuantity = (byte)Integer.parseInt(SQLRes.getObject(E_QUANTITY).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_INHABITANTID)) result += " inhabitant_id="+sInhabitantId + ",";
		if (mStoreFlags.get(E_OWNERID)) result += " owner_id="+sOwnerId + ",";
		if (mStoreFlags.get(E_DESIGNID)) result += " design_id="+sDesignId + ",";
		if (mStoreFlags.get(E_QUANTITY)) result += " quantity="+sQuantity + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_INHABITANTID)) { vars += "inhabitant_id,"; values += sInhabitantId + ",";}
		if (mStoreFlags.get(E_OWNERID)) { vars += "owner_id,"; values += sOwnerId + ",";}
		if (mStoreFlags.get(E_DESIGNID)) { vars += "design_id,"; values += sDesignId + ",";}
		if (mStoreFlags.get(E_QUANTITY)) { vars += "quantity,"; values += sQuantity + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO units "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE units SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM units WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setInhabitantId(int aInhabitantId) {
		this.mStoreFlags.set(E_INHABITANTID);
		this.setSQLaction(2);
		this.sInhabitantId = aInhabitantId;
	}

	public void setOwnerId(int aOwnerId) {
		this.mStoreFlags.set(E_OWNERID);
		this.setSQLaction(2);
		this.sOwnerId = aOwnerId;
	}

	public void setDesignId(int aDesignId) {
		this.mStoreFlags.set(E_DESIGNID);
		this.setSQLaction(2);
		this.sDesignId = aDesignId;
	}

	public void setQuantity(byte aQuantity) {
		this.mStoreFlags.set(E_QUANTITY);
		this.setSQLaction(2);
		this.sQuantity = aQuantity;
	}


	public int getId() {
		return sId;
	}

	public int getInhabitantId() {
		return sInhabitantId;
	}

	public int getOwnerId() {
		return sOwnerId;
	}

	public int getDesignId() {
		return sDesignId;
	}

	public byte getQuantity() {
		return sQuantity;
	}
}

