package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACUnitsTable extends ACUnitsList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACUnitsTable() {
	} 

	public void remove(ACUnits aACUnits) {
		aACUnits.setSQLaction(3);
		appendSQLsync(aACUnits);
		this.ACUnitsVector.remove(aACUnits);
	}

	public ACUnits create() {
		max_id++;
		ACUnits aACUnits = new ACUnits(max_id);
		ACUnitsVector.add(aACUnits); //bypass sort algorithm
		return aACUnits;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACUnits current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACUnits)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACUnits aACUnits) {
		SQLsyncObjects.push(aACUnits);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, inhabitant_id, owner_id, design_id, quantity FROM units ORDER BY id");
			ACUnits loadedSQLACUnits;
			while (res.next()) {
				loadedSQLACUnits = new ACUnits(res);
				ACUnitsVector.add(loadedSQLACUnits); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

