<?
  include "/space/portal/php/portal.php3";
  include "/space/www/notice/lib.php3";

  $portal_id = get_portal_id( $auth_server_con );

  if ($portal_id == "there is a server problem." || $portal_id == "authentification failure" || $portal_id == -1)
  {
    header("Location: redirection.html");
  }

  $name = $HTTP_COOKIE_VARS["NAME"];
?>
<HTML>
<HEAD>
<TITLE>as</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<meta http-equiv="Cache-Control" content="no-cache"/>
<meta http-equiv="Expires" content="0"/>
<meta http-equiv="Pragma" content="no-cache"/>
<LINK REL="stylesheet" HREF="/archspace.css">
<LINK REL="stylesheet" HREF="/cssLib.css">
</HEAD>

<BODY BGCOLOR="000000" LINK="999999" VLINK="999999" ALINK="999999">
<TABLE WIDTH="610" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR ALIGN="CENTER"> 
    <TD><IMG SRC="http://space.magewar.com/image/as_login/mainimg.gif" BORDER="0"></TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD>&nbsp;</TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD> 
      <TABLE WIDTH="400" BORDER="0" CELLSPACING="1" CELLPADDING="0">
        <TR ALIGN="CENTER"> 
          <TD COLSPAN="2" CLASS="maintext">Welcome, <? echo $name; ?>!</TD>
        </TR>
        <TR> 
          <TD>&nbsp;</TD>
          <TD>&nbsp;</TD>
        </TR>
        <TR> 
          <TD COLSPAN="2"><A HREF="/archspace/login.as"><IMG SRC="http://space.magewar.com/image/as_login/bu_enter_as.gif" WIDTH="246" HEIGHT="16" BORDER="0"></A><A HREF="logout.phtml"><IMG SRC="http://space.magewar.com/image/as_login/bu_logout.gif" BORDER="0"></A></TD>
        </TR>
        <TR> 
          <TD>&nbsp;</TD>
          <TD>&nbsp;</TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD HEIGHT="25"><IMG SRC="http://space.magewar.com/image/as_login/line.gif" WIDTH="486" HEIGHT="3"></TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD> 
      <TABLE WIDTH="570" BORDER="0" CELLSPACING="1" CELLPADDING="0">
        <TR VALIGN="TOP"> 
          <TD ALIGN="LEFT"><A HREF=news/news.html><IMG SRC="http://space.magewar.com/image/as_login/new.gif" BORDER=0></A></TD>
          <TD>&nbsp;</TD>
          <TD ALIGN="RIGHT"><IMG SRC="http://space.magewar.com/image/as_login/info.gif" WIDTH="267" HEIGHT="24"></TD>
        </TR>
        <TR> 
          <TD ALIGN="CENTER" WIDTH="280"> 
            <TABLE WIDTH="270" BORDER="0" CELLSPACING="3" CELLPADDING="0">
			<?
//			  notice(3);
			?>
              <TR> 
                <TD WIDTH="5" CLASS="maintext" VALIGN="TOP"><FONT COLOR="666666">&nbsp;</FONT></TD>
                <TD CLASS="maintext" ALIGN=right><A HREF=news/news.html><FONT SIZE=-1>go to archive</FONT></A></TD>
              </TR>
            </TABLE>
          </TD>
          <TD WIDTH="10">&nbsp;</TD>
          <TD WIDTH="280" ALIGN="CENTER"> 
            <TABLE WIDTH="270" BORDER="0" CELLSPACING="1" CELLPADDING="0">
              <TR>
                <TD ROWSPAN="4" WIDTH="148" ALIGN="CENTER"><A HREF="event/010402contest_10xesperados.html"><IMG SRC="http://space.magewar.com/image/as_login/bu_event_contest.gif" BORDER="0"></A></TD>
                <TD WIDTH="117" ALIGN="CENTER"><A HREF="info/concept_sketch.html"><IMG SRC="http://space.magewar.com/image/as_login/concept_sketch.gif" BORDER="0"></A></TD>
              </TR>
              <TR> 
                <TD ALIGN="CENTER" WIDTH="117"><A HREF="beginners/step_by_step.html"><IMG SRC="http://space.magewar.com/image/as_login/bu_stepbystep.gif" WIDTH="99" HEIGHT="23" BORDER="0"></A></TD>
              </TR>
              <TR> 
                <TD ALIGN="CENTER" WIDTH="117"><A HREF="info/contact_us.html"><IMG SRC="http://space.magewar.com/image/as_login/bu_contact_us.gif" BORDER="0"></A></TD>
              </TR>
              <TR> 
                <TD ALIGN="CENTER" WIDTH="117"><A HREF="info/link.html"><IMG SRC="http://space.magewar.com/image/as_login/bu_links.gif" BORDER="0"></A></TD>
              </TR>
            </TABLE>
          </TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD>&nbsp;</TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD CLASS="maintext"><FONT SIZE="2">This site is best viewed with Explorer 
      4.0+ and a resolution of more than 1024x768.<BR>
      Copyright 1999 - 2002 MARITEL.COM <A HREF="http://www.maritel.com" TARGET="_blank"><IMG SRC="http://space.magewar.com/image/as_login/marilogo.gif" WIDTH="71" HEIGHT="15" BORDER="0" ALIGN="ABSMIDDLE"></A> 
      All rights reserved </FONT></TD>
  </TR>
  <TR ALIGN="CENTER"> 
    <TD CLASS="maintext">&nbsp; </TD>
  </TR>
</TABLE>
</BODY>
</HTML>
