<?
  include "libstd.php";
  include "libnotice.php";
  include "libportal.php";

//  setcookie("ID_STRING", "", time() - 3600, "/", "68.11.248.40");
  setcookie("AS_STRING", "", time() - 3600, "/");	// added by thedaz
//  setcookie("ARCHSPACE_HOST", "", time() - 3600, "/", "68.11.248.40");
//  setcookie("ARCHSPACE_PORT", "", time() - 3600, "/", "68.11.248.40");

  header("Location: /index.html");
?>
