<?php

do {
  if($QUERY_STRING) {
    $ad_link = "$QUERY_STRING";
    if(strlen($ad_link) < 20) {
      $ad_link = "http://www.magewar.com/archmage";
      break;
    } 

include "config.php3";
    // Okay, go ahead reward this guy.
//    $dir = explode("/", $HTTP_REFERER);
//    $config_dir = "/bbs/www/" . $dir[3];
//    $config_file = "/bbs/www/" . $dir[3] . "/archmage_config";

//    if(!file_exists($config_file)) break;

//    include "$config_file";

    if($luck != "on") break;

//    if(${$cookie_name} == "")
//      break;				// No cookie detected for this game.

    do {
      $fortune_id = $DB_name . "_L";
      $temp_name = rand();

//      if(${$fortune_id}) {
//	break;
//      }

      srand(mktime());
      $randval = rand() % 20;

      if($randval > 4) break;		// 25% chance message

      $msg1 = array(
	"You feel lucky today.",
	"You found a four-leaf clover at your feet.",
	"A fresh sensation momentarilly occured to you.",
	"A moment of sheer pleasure passed by.",
	"You sensed a total integrity inside of you."
      );

      $msg = $msg1[$randval];

      if(!mysql_connect("", $arch_db_user, $arch_db_pass)) break;
      if(!mysql_select_db($DB_name)) break;

      mysql_query("LOCK TABLES Cookie READ, News WRITE");
      if($result = mysql_query("SELECT id FROM Cookie WHERE cookie='${$cookie_name}'")) {
        list($id) = mysql_fetch_row($result);
        mysql_free_result($result);
	mysql_query("INSERT INTO News (id, news, life) VALUES ($id, '$msg', 1)");
      }
      mysql_query("UNLOCK TABLES");
    } while (0);

    setcookie("$fortune_id", "$temp_name", time() + 3600 * 6, "/");
  } else {
    $ad_link = "http://www.magewar.com/archmage";
  }

} while (0);

Header("Location: $ad_link");
?>
