<br />
<table border="0" cellpadding="2" cellspacing="0" class="checkout" width="100%">
<tr>
    <td>
        <table width="100%" cellspacing="0" cellpadding="4">
        <tr class="diff-header">
            <td align="left"></span><?php echo $author ?></td>
            <td align="right"><?php echo $date ?></td>
        </tr>
        </table>
    </tr>
</tr>
<tr valign="top">
 <td class="diff-log">
  <?php echo $log_print ?>
 </td>
</tr>
</table>
<br />
<table border="0" cellpadding="2" cellspacing="0" class="checkout" width="100%">
<tr>
 <td class="checkout">
