package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACArmiesList {
	protected Vector ACArmiesVector = new Vector();
	
	public void add(ACArmies aACArmies) {
		if (ACArmiesVector.size() == 0) {
			ACArmiesVector.add(0, aACArmies);
			return;
		}
		int middle = (ACArmiesVector.size()-1)/2;
		int index = middle;
		ACArmies current = (ACArmies)ACArmiesVector.get(index);
		while ((index > 0)&&(current.getId() > aACArmies.getId()))
		{
			index--;
			current = (ACArmies)ACArmiesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACArmiesVector.size() - 1 )&&(current.getId() < aACArmies.getId()))
			{
				index++;
				current = (ACArmies)ACArmiesVector.get(index);
			}
		}
		ACArmiesVector.add(index, aACArmies);
	}
	
	public ACArmies fetch(int aID) {
		if (ACArmiesVector.size() == 0) return null;
		int middle = (ACArmiesVector.size()-1)/2;
		int index = middle;
		ACArmies current = (ACArmies)ACArmiesVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACArmies)ACArmiesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACArmiesVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACArmies)ACArmiesVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACArmiesVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACArmies aACArmies) {//done
		this.ACArmiesVector.remove(aACArmies);
	}
	
	public int length() {//done
		return this.ACArmiesVector.size();
	}
	
	public ACArmies get(int aNumber) {//done
		return (ACArmies)ACArmiesVector.get(aNumber);
	}

	public ACArmiesList findByName(java.lang.String aName) {
		ACArmiesList aACArmiesList = new ACArmiesList();
		ACArmies current;
		for (int i = 0; i < this.ACArmiesVector.size(); i++) {
			current = (ACArmies)this.ACArmiesVector.get(i);
			if (aName.equals(current.getName())) {
				aACArmiesList.add(current);
			}
		}
		return aACArmiesList;
	}

	public ACArmiesList findByTerritoryId(int aTerritoryId) {
		ACArmiesList aACArmiesList = new ACArmiesList();
		ACArmies current;
		for (int i = 0; i < this.ACArmiesVector.size(); i++) {
			current = (ACArmies)this.ACArmiesVector.get(i);
			if (aTerritoryId == current.getTerritoryId()) {
				aACArmiesList.add(current);
			}
		}
		return aACArmiesList;
	}

	public ACArmiesList findByOwnerId(int aOwnerId) {
		ACArmiesList aACArmiesList = new ACArmiesList();
		ACArmies current;
		for (int i = 0; i < this.ACArmiesVector.size(); i++) {
			current = (ACArmies)this.ACArmiesVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACArmiesList.add(current);
			}
		}
		return aACArmiesList;
	}

	public ACArmiesList findByCommandingSquadId(int aCommandingSquadId) {
		ACArmiesList aACArmiesList = new ACArmiesList();
		ACArmies current;
		for (int i = 0; i < this.ACArmiesVector.size(); i++) {
			current = (ACArmies)this.ACArmiesVector.get(i);
			if (aCommandingSquadId == current.getCommandingSquadId()) {
				aACArmiesList.add(current);
			}
		}
		return aACArmiesList;
	}
}

