package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACArmies {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private java.lang.String sName;
	private int sTerritoryId;
	private int sOwnerId;
	private int sCommandingSquadId;

	public static ACArmiesTable mTable;
	public static final short E_ID=0;
	public static final short E_NAME=1;
	public static final short E_TERRITORYID=2;
	public static final short E_OWNERID=3;
	public static final short E_COMMANDINGSQUADID=4;

	public ACArmies(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACArmies(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sName = SQLRes.getObject(E_NAME).toString();
			sTerritoryId = (int)Integer.parseInt(SQLRes.getObject(E_TERRITORYID).toString());
			sOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OWNERID).toString());
			sCommandingSquadId = (int)Integer.parseInt(SQLRes.getObject(E_COMMANDINGSQUADID).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_TERRITORYID)) result += " territory_id="+sTerritoryId + ",";
		if (mStoreFlags.get(E_OWNERID)) result += " owner_id="+sOwnerId + ",";
		if (mStoreFlags.get(E_COMMANDINGSQUADID)) result += " commanding_squad_id="+sCommandingSquadId + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_TERRITORYID)) { vars += "territory_id,"; values += sTerritoryId + ",";}
		if (mStoreFlags.get(E_OWNERID)) { vars += "owner_id,"; values += sOwnerId + ",";}
		if (mStoreFlags.get(E_COMMANDINGSQUADID)) { vars += "commanding_squad_id,"; values += sCommandingSquadId + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO armies "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE armies SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM armies WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setTerritoryId(int aTerritoryId) {
		this.mStoreFlags.set(E_TERRITORYID);
		this.setSQLaction(2);
		this.sTerritoryId = aTerritoryId;
	}

	public void setOwnerId(int aOwnerId) {
		this.mStoreFlags.set(E_OWNERID);
		this.setSQLaction(2);
		this.sOwnerId = aOwnerId;
	}

	public void setCommandingSquadId(int aCommandingSquadId) {
		this.mStoreFlags.set(E_COMMANDINGSQUADID);
		this.setSQLaction(2);
		this.sCommandingSquadId = aCommandingSquadId;
	}


	public int getId() {
		return sId;
	}

	public java.lang.String getName() {
		return sName;
	}

	public int getTerritoryId() {
		return sTerritoryId;
	}

	public int getOwnerId() {
		return sOwnerId;
	}

	public int getCommandingSquadId() {
		return sCommandingSquadId;
	}
}

