package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACArmiesTable extends ACArmiesList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACArmiesTable() {
	} 

	public void remove(ACArmies aACArmies) {
		aACArmies.setSQLaction(3);
		appendSQLsync(aACArmies);
		this.ACArmiesVector.remove(aACArmies);
	}

	public ACArmies create() {
		max_id++;
		ACArmies aACArmies = new ACArmies(max_id);
		ACArmiesVector.add(aACArmies); //bypass sort algorithm
		return aACArmies;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACArmies current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACArmies)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACArmies aACArmies) {
		SQLsyncObjects.push(aACArmies);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, name, territory_id, owner_id, commanding_squad_id FROM armies ORDER BY id");
			ACArmies loadedSQLACArmies;
			while (res.next()) {
				loadedSQLACArmies = new ACArmies(res);
				ACArmiesVector.add(loadedSQLACArmies); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

