package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACBattles {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sAttacker;
	private int sDefender;
	private byte sOutcome;
	private int sTime;

	public static ACBattlesTable mTable;
	public static final short E_ID=0;
	public static final short E_ATTACKER=1;
	public static final short E_DEFENDER=2;
	public static final short E_OUTCOME=3;
	public static final short E_TIME=4;

	public ACBattles(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACBattles(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sAttacker = (int)Integer.parseInt(SQLRes.getObject(E_ATTACKER).toString());
			sDefender = (int)Integer.parseInt(SQLRes.getObject(E_DEFENDER).toString());
			sOutcome = (byte)Integer.parseInt(SQLRes.getObject(E_OUTCOME).toString());
			sTime = (int)Integer.parseInt(SQLRes.getObject(E_TIME).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_ATTACKER)) result += " attacker="+sAttacker + ",";
		if (mStoreFlags.get(E_DEFENDER)) result += " defender="+sDefender + ",";
		if (mStoreFlags.get(E_OUTCOME)) result += " outcome="+sOutcome + ",";
		if (mStoreFlags.get(E_TIME)) result += " time="+sTime + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_ATTACKER)) { vars += "attacker,"; values += sAttacker + ",";}
		if (mStoreFlags.get(E_DEFENDER)) { vars += "defender,"; values += sDefender + ",";}
		if (mStoreFlags.get(E_OUTCOME)) { vars += "outcome,"; values += sOutcome + ",";}
		if (mStoreFlags.get(E_TIME)) { vars += "time,"; values += sTime + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO battles "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE battles SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM battles WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setAttacker(int aAttacker) {
		this.mStoreFlags.set(E_ATTACKER);
		this.setSQLaction(2);
		this.sAttacker = aAttacker;
	}

	public void setDefender(int aDefender) {
		this.mStoreFlags.set(E_DEFENDER);
		this.setSQLaction(2);
		this.sDefender = aDefender;
	}

	public void setOutcome(byte aOutcome) {
		this.mStoreFlags.set(E_OUTCOME);
		this.setSQLaction(2);
		this.sOutcome = aOutcome;
	}

	public void setTime(int aTime) {
		this.mStoreFlags.set(E_TIME);
		this.setSQLaction(2);
		this.sTime = aTime;
	}


	public int getId() {
		return sId;
	}

	public int getAttacker() {
		return sAttacker;
	}

	public int getDefender() {
		return sDefender;
	}

	public byte getOutcome() {
		return sOutcome;
	}

	public int getTime() {
		return sTime;
	}
}

