package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACBattlesTable extends ACBattlesList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACBattlesTable() {
	} 

	public void remove(ACBattles aACBattles) {
		aACBattles.setSQLaction(3);
		appendSQLsync(aACBattles);
		this.ACBattlesVector.remove(aACBattles);
	}

	public ACBattles create() {
		max_id++;
		ACBattles aACBattles = new ACBattles(max_id);
		ACBattlesVector.add(aACBattles); //bypass sort algorithm
		return aACBattles;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACBattles current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACBattles)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACBattles aACBattles) {
		SQLsyncObjects.push(aACBattles);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, attacker, defender, outcome, time FROM battles ORDER BY id");
			ACBattles loadedSQLACBattles;
			while (res.next()) {
				loadedSQLACBattles = new ACBattles(res);
				ACBattlesVector.add(loadedSQLACBattles); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

