package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACBattlesList {
	protected Vector ACBattlesVector = new Vector();
	
	public void add(ACBattles aACBattles) {
		if (ACBattlesVector.size() == 0) {
			ACBattlesVector.add(0, aACBattles);
			return;
		}
		int middle = (ACBattlesVector.size()-1)/2;
		int index = middle;
		ACBattles current = (ACBattles)ACBattlesVector.get(index);
		while ((index > 0)&&(current.getId() > aACBattles.getId()))
		{
			index--;
			current = (ACBattles)ACBattlesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACBattlesVector.size() - 1 )&&(current.getId() < aACBattles.getId()))
			{
				index++;
				current = (ACBattles)ACBattlesVector.get(index);
			}
		}
		ACBattlesVector.add(index, aACBattles);
	}
	
	public ACBattles fetch(int aID) {
		if (ACBattlesVector.size() == 0) return null;
		int middle = (ACBattlesVector.size()-1)/2;
		int index = middle;
		ACBattles current = (ACBattles)ACBattlesVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACBattles)ACBattlesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACBattlesVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACBattles)ACBattlesVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACBattlesVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACBattles aACBattles) {//done
		this.ACBattlesVector.remove(aACBattles);
	}
	
	public int length() {//done
		return this.ACBattlesVector.size();
	}
	
	public ACBattles get(int aNumber) {//done
		return (ACBattles)ACBattlesVector.get(aNumber);
	}

	public ACBattlesList findByAttacker(int aAttacker) {
		ACBattlesList aACBattlesList = new ACBattlesList();
		ACBattles current;
		for (int i = 0; i < this.ACBattlesVector.size(); i++) {
			current = (ACBattles)this.ACBattlesVector.get(i);
			if (aAttacker == current.getAttacker()) {
				aACBattlesList.add(current);
			}
		}
		return aACBattlesList;
	}

	public ACBattlesList findByDefender(int aDefender) {
		ACBattlesList aACBattlesList = new ACBattlesList();
		ACBattles current;
		for (int i = 0; i < this.ACBattlesVector.size(); i++) {
			current = (ACBattles)this.ACBattlesVector.get(i);
			if (aDefender == current.getDefender()) {
				aACBattlesList.add(current);
			}
		}
		return aACBattlesList;
	}

	public ACBattlesList findByOutcome(byte aOutcome) {
		ACBattlesList aACBattlesList = new ACBattlesList();
		ACBattles current;
		for (int i = 0; i < this.ACBattlesVector.size(); i++) {
			current = (ACBattles)this.ACBattlesVector.get(i);
			if (aOutcome == current.getOutcome()) {
				aACBattlesList.add(current);
			}
		}
		return aACBattlesList;
	}

	public ACBattlesList findByTime(int aTime) {
		ACBattlesList aACBattlesList = new ACBattlesList();
		ACBattles current;
		for (int i = 0; i < this.ACBattlesVector.size(); i++) {
			current = (ACBattles)this.ACBattlesVector.get(i);
			if (aTime == current.getTime()) {
				aACBattlesList.add(current);
			}
		}
		return aACBattlesList;
	}
}

