package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Table generated by zbyte's sql to java script
public class ACCommandersTable extends ACCommandersList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACCommandersTable() {
	} 

	public void remove(ACCommanders aACCommanders) {
		aACCommanders.setSQLaction(3);
		appendSQLsync(aACCommanders);
		this.ACCommandersVector.remove(aACCommanders);
	}

	public ACCommanders create() {
		max_id++;
		ACCommanders aACCommanders = new ACCommanders(max_id);
		ACCommandersVector.add(aACCommanders); //bypass sort algorithm
		return aACCommanders;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACCommanders current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACCommanders)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACCommanders aACCommanders) {
		SQLsyncObjects.push(aACCommanders);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, owner_id, name, level, abilities_hash, experience, max_command, melee, range, barrage, detection, defense, mobility, pillage, plunder, blockade, morale_boost FROM commanders ORDER BY id");
			ACCommanders loadedSQLACCommanders;
			while (res.next()) {
				loadedSQLACCommanders = new ACCommanders(res);
				ACCommandersVector.add(loadedSQLACCommanders); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

