package org.archcave.classes;
import java.util.Vector;
import org.archcave.libs.JHash;

//List generated by zbyte's sql to java script
public class ACCommandersList {
	protected Vector ACCommandersVector = new Vector();
	
	public void add(ACCommanders aACCommanders) {
		if (ACCommandersVector.size() == 0) {
			ACCommandersVector.add(0, aACCommanders);
			return;
		}
		int middle = (ACCommandersVector.size()-1)/2;
		int index = middle;
		ACCommanders current = (ACCommanders)ACCommandersVector.get(index);
		while ((index > 0)&&(current.getId() > aACCommanders.getId()))
		{
			index--;
			current = (ACCommanders)ACCommandersVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACCommandersVector.size() - 1 )&&(current.getId() < aACCommanders.getId()))
			{
				index++;
				current = (ACCommanders)ACCommandersVector.get(index);
			}
		}
		ACCommandersVector.add(index, aACCommanders);
	}
	
	public ACCommanders fetch(int aID) {
		if (ACCommandersVector.size() == 0) return null;
		int middle = (ACCommandersVector.size()-1)/2;
		int index = middle;
		ACCommanders current = (ACCommanders)ACCommandersVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACCommanders)ACCommandersVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACCommandersVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACCommanders)ACCommandersVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACCommandersVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACCommanders aACCommanders) {//done
		this.ACCommandersVector.remove(aACCommanders);
	}
	
	public int length() {//done
		return this.ACCommandersVector.size();
	}
	
	public ACCommanders get(int aNumber) {//done
		return (ACCommanders)ACCommandersVector.get(aNumber);
	}

	public ACCommandersList findByOwnerId(int aOwnerId) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByName(java.lang.String aName) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aName.equals(current.getName())) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByLevel(byte aLevel) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aLevel == current.getLevel()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByAbilitiesHash(org.archcave.libs.JHash aAbilitiesHash) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aAbilitiesHash == current.getAbilitiesHash()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByExperience(int aExperience) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aExperience == current.getExperience()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByMaxCommand(byte aMaxCommand) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aMaxCommand == current.getMaxCommand()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByMelee(byte aMelee) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aMelee == current.getMelee()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByRange(byte aRange) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aRange == current.getRange()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByBarrage(byte aBarrage) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aBarrage == current.getBarrage()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByDetection(byte aDetection) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aDetection == current.getDetection()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByDefense(byte aDefense) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aDefense == current.getDefense()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByMobility(byte aMobility) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aMobility == current.getMobility()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByPillage(byte aPillage) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aPillage == current.getPillage()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByPlunder(byte aPlunder) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aPlunder == current.getPlunder()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByBlockade(byte aBlockade) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aBlockade == current.getBlockade()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}

	public ACCommandersList findByMoraleBoost(byte aMoraleBoost) {
		ACCommandersList aACCommandersList = new ACCommandersList();
		ACCommanders current;
		for (int i = 0; i < this.ACCommandersVector.size(); i++) {
			current = (ACCommanders)this.ACCommandersVector.get(i);
			if (aMoraleBoost == current.getMoraleBoost()) {
				aACCommandersList.add(current);
			}
		}
		return aACCommandersList;
	}
}

