package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Object generated by zbyte's sql to java script
public class ACCommanders {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sOwnerId;
	private java.lang.String sName;
	private byte sLevel;
	private org.archcave.libs.JHash sAbilitiesHash;
	private int sExperience;
	private byte sMaxCommand;
	private byte sMelee;
	private byte sRange;
	private byte sBarrage;
	private byte sDetection;
	private byte sDefense;
	private byte sMobility;
	private byte sPillage;
	private byte sPlunder;
	private byte sBlockade;
	private byte sMoraleBoost;

	public static ACCommandersTable mTable;
	public static final short E_ID=0;
	public static final short E_OWNERID=1;
	public static final short E_NAME=2;
	public static final short E_LEVEL=3;
	public static final short E_ABILITIESHASH=4;
	public static final short E_EXPERIENCE=5;
	public static final short E_MAXCOMMAND=6;
	public static final short E_MELEE=7;
	public static final short E_RANGE=8;
	public static final short E_BARRAGE=9;
	public static final short E_DETECTION=10;
	public static final short E_DEFENSE=11;
	public static final short E_MOBILITY=12;
	public static final short E_PILLAGE=13;
	public static final short E_PLUNDER=14;
	public static final short E_BLOCKADE=15;
	public static final short E_MORALEBOOST=16;

	public ACCommanders(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACCommanders(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OWNERID).toString());
			sName = SQLRes.getObject(E_NAME).toString();
			sLevel = (byte)Integer.parseInt(SQLRes.getObject(E_LEVEL).toString());
			sAbilitiesHash = new JHash(SQLRes.getObject(E_ABILITIESHASH).toString());
			sExperience = (int)Integer.parseInt(SQLRes.getObject(E_EXPERIENCE).toString());
			sMaxCommand = (byte)Integer.parseInt(SQLRes.getObject(E_MAXCOMMAND).toString());
			sMelee = (byte)Integer.parseInt(SQLRes.getObject(E_MELEE).toString());
			sRange = (byte)Integer.parseInt(SQLRes.getObject(E_RANGE).toString());
			sBarrage = (byte)Integer.parseInt(SQLRes.getObject(E_BARRAGE).toString());
			sDetection = (byte)Integer.parseInt(SQLRes.getObject(E_DETECTION).toString());
			sDefense = (byte)Integer.parseInt(SQLRes.getObject(E_DEFENSE).toString());
			sMobility = (byte)Integer.parseInt(SQLRes.getObject(E_MOBILITY).toString());
			sPillage = (byte)Integer.parseInt(SQLRes.getObject(E_PILLAGE).toString());
			sPlunder = (byte)Integer.parseInt(SQLRes.getObject(E_PLUNDER).toString());
			sBlockade = (byte)Integer.parseInt(SQLRes.getObject(E_BLOCKADE).toString());
			sMoraleBoost = (byte)Integer.parseInt(SQLRes.getObject(E_MORALEBOOST).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_OWNERID)) result += " owner_id="+sOwnerId + ",";
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_LEVEL)) result += " level="+sLevel + ",";
		if (mStoreFlags.get(E_ABILITIESHASH)) result += " abilities_hash="+sAbilitiesHash + ",";
		if (mStoreFlags.get(E_EXPERIENCE)) result += " experience="+sExperience + ",";
		if (mStoreFlags.get(E_MAXCOMMAND)) result += " max_command="+sMaxCommand + ",";
		if (mStoreFlags.get(E_MELEE)) result += " melee="+sMelee + ",";
		if (mStoreFlags.get(E_RANGE)) result += " range="+sRange + ",";
		if (mStoreFlags.get(E_BARRAGE)) result += " barrage="+sBarrage + ",";
		if (mStoreFlags.get(E_DETECTION)) result += " detection="+sDetection + ",";
		if (mStoreFlags.get(E_DEFENSE)) result += " defense="+sDefense + ",";
		if (mStoreFlags.get(E_MOBILITY)) result += " mobility="+sMobility + ",";
		if (mStoreFlags.get(E_PILLAGE)) result += " pillage="+sPillage + ",";
		if (mStoreFlags.get(E_PLUNDER)) result += " plunder="+sPlunder + ",";
		if (mStoreFlags.get(E_BLOCKADE)) result += " blockade="+sBlockade + ",";
		if (mStoreFlags.get(E_MORALEBOOST)) result += " morale_boost="+sMoraleBoost + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_OWNERID)) { vars += "owner_id,"; values += sOwnerId + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_LEVEL)) { vars += "level,"; values += sLevel + ",";}
		if (mStoreFlags.get(E_ABILITIESHASH)) { vars += "abilities_hash,"; values += sAbilitiesHash + ",";}
		if (mStoreFlags.get(E_EXPERIENCE)) { vars += "experience,"; values += sExperience + ",";}
		if (mStoreFlags.get(E_MAXCOMMAND)) { vars += "max_command,"; values += sMaxCommand + ",";}
		if (mStoreFlags.get(E_MELEE)) { vars += "melee,"; values += sMelee + ",";}
		if (mStoreFlags.get(E_RANGE)) { vars += "range,"; values += sRange + ",";}
		if (mStoreFlags.get(E_BARRAGE)) { vars += "barrage,"; values += sBarrage + ",";}
		if (mStoreFlags.get(E_DETECTION)) { vars += "detection,"; values += sDetection + ",";}
		if (mStoreFlags.get(E_DEFENSE)) { vars += "defense,"; values += sDefense + ",";}
		if (mStoreFlags.get(E_MOBILITY)) { vars += "mobility,"; values += sMobility + ",";}
		if (mStoreFlags.get(E_PILLAGE)) { vars += "pillage,"; values += sPillage + ",";}
		if (mStoreFlags.get(E_PLUNDER)) { vars += "plunder,"; values += sPlunder + ",";}
		if (mStoreFlags.get(E_BLOCKADE)) { vars += "blockade,"; values += sBlockade + ",";}
		if (mStoreFlags.get(E_MORALEBOOST)) { vars += "morale_boost,"; values += sMoraleBoost + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO commanders "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE commanders SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM commanders WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setOwnerId(int aOwnerId) {
		this.mStoreFlags.set(E_OWNERID);
		this.setSQLaction(2);
		this.sOwnerId = aOwnerId;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setLevel(byte aLevel) {
		this.mStoreFlags.set(E_LEVEL);
		this.setSQLaction(2);
		this.sLevel = aLevel;
	}

	public void setAbilitiesHash(org.archcave.libs.JHash aAbilitiesHash) {
		this.mStoreFlags.set(E_ABILITIESHASH);
		this.setSQLaction(2);
		this.sAbilitiesHash = aAbilitiesHash;
	}

	public void setExperience(int aExperience) {
		this.mStoreFlags.set(E_EXPERIENCE);
		this.setSQLaction(2);
		this.sExperience = aExperience;
	}

	public void setMaxCommand(byte aMaxCommand) {
		this.mStoreFlags.set(E_MAXCOMMAND);
		this.setSQLaction(2);
		this.sMaxCommand = aMaxCommand;
	}

	public void setMelee(byte aMelee) {
		this.mStoreFlags.set(E_MELEE);
		this.setSQLaction(2);
		this.sMelee = aMelee;
	}

	public void setRange(byte aRange) {
		this.mStoreFlags.set(E_RANGE);
		this.setSQLaction(2);
		this.sRange = aRange;
	}

	public void setBarrage(byte aBarrage) {
		this.mStoreFlags.set(E_BARRAGE);
		this.setSQLaction(2);
		this.sBarrage = aBarrage;
	}

	public void setDetection(byte aDetection) {
		this.mStoreFlags.set(E_DETECTION);
		this.setSQLaction(2);
		this.sDetection = aDetection;
	}

	public void setDefense(byte aDefense) {
		this.mStoreFlags.set(E_DEFENSE);
		this.setSQLaction(2);
		this.sDefense = aDefense;
	}

	public void setMobility(byte aMobility) {
		this.mStoreFlags.set(E_MOBILITY);
		this.setSQLaction(2);
		this.sMobility = aMobility;
	}

	public void setPillage(byte aPillage) {
		this.mStoreFlags.set(E_PILLAGE);
		this.setSQLaction(2);
		this.sPillage = aPillage;
	}

	public void setPlunder(byte aPlunder) {
		this.mStoreFlags.set(E_PLUNDER);
		this.setSQLaction(2);
		this.sPlunder = aPlunder;
	}

	public void setBlockade(byte aBlockade) {
		this.mStoreFlags.set(E_BLOCKADE);
		this.setSQLaction(2);
		this.sBlockade = aBlockade;
	}

	public void setMoraleBoost(byte aMoraleBoost) {
		this.mStoreFlags.set(E_MORALEBOOST);
		this.setSQLaction(2);
		this.sMoraleBoost = aMoraleBoost;
	}


	public int getId() {
		return sId;
	}

	public int getOwnerId() {
		return sOwnerId;
	}

	public java.lang.String getName() {
		return sName;
	}

	public byte getLevel() {
		return sLevel;
	}

	public org.archcave.libs.JHash getAbilitiesHash() {
		return sAbilitiesHash;
	}

	public int getExperience() {
		return sExperience;
	}

	public byte getMaxCommand() {
		return sMaxCommand;
	}

	public byte getMelee() {
		return sMelee;
	}

	public byte getRange() {
		return sRange;
	}

	public byte getBarrage() {
		return sBarrage;
	}

	public byte getDetection() {
		return sDetection;
	}

	public byte getDefense() {
		return sDefense;
	}

	public byte getMobility() {
		return sMobility;
	}

	public byte getPillage() {
		return sPillage;
	}

	public byte getPlunder() {
		return sPlunder;
	}

	public byte getBlockade() {
		return sBlockade;
	}

	public byte getMoraleBoost() {
		return sMoraleBoost;
	}
}

