package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACDesignsList {
	protected Vector ACDesignsVector = new Vector();
	
	public void add(ACDesigns aACDesigns) {
		if (ACDesignsVector.size() == 0) {
			ACDesignsVector.add(0, aACDesigns);
			return;
		}
		int middle = (ACDesignsVector.size()-1)/2;
		int index = middle;
		ACDesigns current = (ACDesigns)ACDesignsVector.get(index);
		while ((index > 0)&&(current.getId() > aACDesigns.getId()))
		{
			index--;
			current = (ACDesigns)ACDesignsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACDesignsVector.size() - 1 )&&(current.getId() < aACDesigns.getId()))
			{
				index++;
				current = (ACDesigns)ACDesignsVector.get(index);
			}
		}
		ACDesignsVector.add(index, aACDesigns);
	}
	
	public ACDesigns fetch(int aID) {
		if (ACDesignsVector.size() == 0) return null;
		int middle = (ACDesignsVector.size()-1)/2;
		int index = middle;
		ACDesigns current = (ACDesigns)ACDesignsVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACDesigns)ACDesignsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACDesignsVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACDesigns)ACDesignsVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACDesignsVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACDesigns aACDesigns) {//done
		this.ACDesignsVector.remove(aACDesigns);
	}
	
	public int length() {//done
		return this.ACDesignsVector.size();
	}
	
	public ACDesigns get(int aNumber) {//done
		return (ACDesigns)ACDesignsVector.get(aNumber);
	}

	public ACDesignsList findByOwnerId(int aOwnerId) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByName(java.lang.String aName) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aName.equals(current.getName())) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByChasis(byte aChasis) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aChasis == current.getChasis()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByWeapon1Id(short aWeapon1Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aWeapon1Id == current.getWeapon1Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByWeapon2Id(short aWeapon2Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aWeapon2Id == current.getWeapon2Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByWeapon3Id(short aWeapon3Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aWeapon3Id == current.getWeapon3Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByArmor1Id(short aArmor1Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aArmor1Id == current.getArmor1Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByArmor2Id(short aArmor2Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aArmor2Id == current.getArmor2Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findByArmor3Id(short aArmor3Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aArmor3Id == current.getArmor3Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findBySpecial1Id(short aSpecial1Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aSpecial1Id == current.getSpecial1Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findBySpecial2Id(short aSpecial2Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aSpecial2Id == current.getSpecial2Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}

	public ACDesignsList findBySpecial3Id(short aSpecial3Id) {
		ACDesignsList aACDesignsList = new ACDesignsList();
		ACDesigns current;
		for (int i = 0; i < this.ACDesignsVector.size(); i++) {
			current = (ACDesigns)this.ACDesignsVector.get(i);
			if (aSpecial3Id == current.getSpecial3Id()) {
				aACDesignsList.add(current);
			}
		}
		return aACDesignsList;
	}
}

