package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACEvents {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sEventId;
	private int sOwnerId;
	private int sStartTime;

	public static ACEventsTable mTable;
	public static final short E_ID=0;
	public static final short E_EVENTID=1;
	public static final short E_OWNERID=2;
	public static final short E_STARTTIME=3;

	public ACEvents(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACEvents(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sEventId = (int)Integer.parseInt(SQLRes.getObject(E_EVENTID).toString());
			sOwnerId = (int)Integer.parseInt(SQLRes.getObject(E_OWNERID).toString());
			sStartTime = (int)Integer.parseInt(SQLRes.getObject(E_STARTTIME).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_EVENTID)) result += " event_id="+sEventId + ",";
		if (mStoreFlags.get(E_OWNERID)) result += " owner_id="+sOwnerId + ",";
		if (mStoreFlags.get(E_STARTTIME)) result += " start_time="+sStartTime + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_EVENTID)) { vars += "event_id,"; values += sEventId + ",";}
		if (mStoreFlags.get(E_OWNERID)) { vars += "owner_id,"; values += sOwnerId + ",";}
		if (mStoreFlags.get(E_STARTTIME)) { vars += "start_time,"; values += sStartTime + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO events "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE events SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM events WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setEventId(int aEventId) {
		this.mStoreFlags.set(E_EVENTID);
		this.setSQLaction(2);
		this.sEventId = aEventId;
	}

	public void setOwnerId(int aOwnerId) {
		this.mStoreFlags.set(E_OWNERID);
		this.setSQLaction(2);
		this.sOwnerId = aOwnerId;
	}

	public void setStartTime(int aStartTime) {
		this.mStoreFlags.set(E_STARTTIME);
		this.setSQLaction(2);
		this.sStartTime = aStartTime;
	}


	public int getId() {
		return sId;
	}

	public int getEventId() {
		return sEventId;
	}

	public int getOwnerId() {
		return sOwnerId;
	}

	public int getStartTime() {
		return sStartTime;
	}
}

