package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACEventsList {
	protected Vector ACEventsVector = new Vector();
	
	public void add(ACEvents aACEvents) {
		if (ACEventsVector.size() == 0) {
			ACEventsVector.add(0, aACEvents);
			return;
		}
		int middle = (ACEventsVector.size()-1)/2;
		int index = middle;
		ACEvents current = (ACEvents)ACEventsVector.get(index);
		while ((index > 0)&&(current.getId() > aACEvents.getId()))
		{
			index--;
			current = (ACEvents)ACEventsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACEventsVector.size() - 1 )&&(current.getId() < aACEvents.getId()))
			{
				index++;
				current = (ACEvents)ACEventsVector.get(index);
			}
		}
		ACEventsVector.add(index, aACEvents);
	}
	
	public ACEvents fetch(int aID) {
		if (ACEventsVector.size() == 0) return null;
		int middle = (ACEventsVector.size()-1)/2;
		int index = middle;
		ACEvents current = (ACEvents)ACEventsVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACEvents)ACEventsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACEventsVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACEvents)ACEventsVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACEventsVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACEvents aACEvents) {//done
		this.ACEventsVector.remove(aACEvents);
	}
	
	public int length() {//done
		return this.ACEventsVector.size();
	}
	
	public ACEvents get(int aNumber) {//done
		return (ACEvents)ACEventsVector.get(aNumber);
	}

	public ACEventsList findByEventId(int aEventId) {
		ACEventsList aACEventsList = new ACEventsList();
		ACEvents current;
		for (int i = 0; i < this.ACEventsVector.size(); i++) {
			current = (ACEvents)this.ACEventsVector.get(i);
			if (aEventId == current.getEventId()) {
				aACEventsList.add(current);
			}
		}
		return aACEventsList;
	}

	public ACEventsList findByOwnerId(int aOwnerId) {
		ACEventsList aACEventsList = new ACEventsList();
		ACEvents current;
		for (int i = 0; i < this.ACEventsVector.size(); i++) {
			current = (ACEvents)this.ACEventsVector.get(i);
			if (aOwnerId == current.getOwnerId()) {
				aACEventsList.add(current);
			}
		}
		return aACEventsList;
	}

	public ACEventsList findByStartTime(int aStartTime) {
		ACEventsList aACEventsList = new ACEventsList();
		ACEvents current;
		for (int i = 0; i < this.ACEventsVector.size(); i++) {
			current = (ACEvents)this.ACEventsVector.get(i);
			if (aStartTime == current.getStartTime()) {
				aACEventsList.add(current);
			}
		}
		return aACEventsList;
	}
}

