package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACHerosTable extends ACHerosList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACHerosTable() {
	} 

	public void remove(ACHeros aACHeros) {
		aACHeros.setSQLaction(3);
		appendSQLsync(aACHeros);
		this.ACHerosVector.remove(aACHeros);
	}

	public ACHeros create() {
		max_id++;
		ACHeros aACHeros = new ACHeros(max_id);
		ACHerosVector.add(aACHeros); //bypass sort algorithm
		return aACHeros;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACHeros current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACHeros)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACHeros aACHeros) {
		SQLsyncObjects.push(aACHeros);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, army_id, hero_id, vitality, hp, moves FROM heros ORDER BY id");
			ACHeros loadedSQLACHeros;
			while (res.next()) {
				loadedSQLACHeros = new ACHeros(res);
				ACHerosVector.add(loadedSQLACHeros); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

