package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACHerosList {
	protected Vector ACHerosVector = new Vector();
	
	public void add(ACHeros aACHeros) {
		if (ACHerosVector.size() == 0) {
			ACHerosVector.add(0, aACHeros);
			return;
		}
		int middle = (ACHerosVector.size()-1)/2;
		int index = middle;
		ACHeros current = (ACHeros)ACHerosVector.get(index);
		while ((index > 0)&&(current.getId() > aACHeros.getId()))
		{
			index--;
			current = (ACHeros)ACHerosVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACHerosVector.size() - 1 )&&(current.getId() < aACHeros.getId()))
			{
				index++;
				current = (ACHeros)ACHerosVector.get(index);
			}
		}
		ACHerosVector.add(index, aACHeros);
	}
	
	public ACHeros fetch(int aID) {
		if (ACHerosVector.size() == 0) return null;
		int middle = (ACHerosVector.size()-1)/2;
		int index = middle;
		ACHeros current = (ACHeros)ACHerosVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACHeros)ACHerosVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACHerosVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACHeros)ACHerosVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACHerosVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACHeros aACHeros) {//done
		this.ACHerosVector.remove(aACHeros);
	}
	
	public int length() {//done
		return this.ACHerosVector.size();
	}
	
	public ACHeros get(int aNumber) {//done
		return (ACHeros)ACHerosVector.get(aNumber);
	}

	public ACHerosList findByArmyId(int aArmyId) {
		ACHerosList aACHerosList = new ACHerosList();
		ACHeros current;
		for (int i = 0; i < this.ACHerosVector.size(); i++) {
			current = (ACHeros)this.ACHerosVector.get(i);
			if (aArmyId == current.getArmyId()) {
				aACHerosList.add(current);
			}
		}
		return aACHerosList;
	}

	public ACHerosList findByHeroId(int aHeroId) {
		ACHerosList aACHerosList = new ACHerosList();
		ACHeros current;
		for (int i = 0; i < this.ACHerosVector.size(); i++) {
			current = (ACHeros)this.ACHerosVector.get(i);
			if (aHeroId == current.getHeroId()) {
				aACHerosList.add(current);
			}
		}
		return aACHerosList;
	}

	public ACHerosList findByVitality(byte aVitality) {
		ACHerosList aACHerosList = new ACHerosList();
		ACHeros current;
		for (int i = 0; i < this.ACHerosVector.size(); i++) {
			current = (ACHeros)this.ACHerosVector.get(i);
			if (aVitality == current.getVitality()) {
				aACHerosList.add(current);
			}
		}
		return aACHerosList;
	}

	public ACHerosList findByHp(int aHp) {
		ACHerosList aACHerosList = new ACHerosList();
		ACHeros current;
		for (int i = 0; i < this.ACHerosVector.size(); i++) {
			current = (ACHeros)this.ACHerosVector.get(i);
			if (aHp == current.getHp()) {
				aACHerosList.add(current);
			}
		}
		return aACHerosList;
	}

	public ACHerosList findByMoves(byte aMoves) {
		ACHerosList aACHerosList = new ACHerosList();
		ACHeros current;
		for (int i = 0; i < this.ACHerosVector.size(); i++) {
			current = (ACHeros)this.ACHerosVector.get(i);
			if (aMoves == current.getMoves()) {
				aACHerosList.add(current);
			}
		}
		return aACHerosList;
	}
}

