package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACHeros {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sArmyId;
	private int sHeroId;
	private byte sVitality;
	private int sHp;
	private byte sMoves;

	public static ACHerosTable mTable;
	public static final short E_ID=0;
	public static final short E_ARMYID=1;
	public static final short E_HEROID=2;
	public static final short E_VITALITY=3;
	public static final short E_HP=4;
	public static final short E_MOVES=5;

	public ACHeros(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACHeros(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sArmyId = (int)Integer.parseInt(SQLRes.getObject(E_ARMYID).toString());
			sHeroId = (int)Integer.parseInt(SQLRes.getObject(E_HEROID).toString());
			sVitality = (byte)Integer.parseInt(SQLRes.getObject(E_VITALITY).toString());
			sHp = (int)Integer.parseInt(SQLRes.getObject(E_HP).toString());
			sMoves = (byte)Integer.parseInt(SQLRes.getObject(E_MOVES).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_ARMYID)) result += " army_id="+sArmyId + ",";
		if (mStoreFlags.get(E_HEROID)) result += " hero_id="+sHeroId + ",";
		if (mStoreFlags.get(E_VITALITY)) result += " vitality="+sVitality + ",";
		if (mStoreFlags.get(E_HP)) result += " hp="+sHp + ",";
		if (mStoreFlags.get(E_MOVES)) result += " moves="+sMoves + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_ARMYID)) { vars += "army_id,"; values += sArmyId + ",";}
		if (mStoreFlags.get(E_HEROID)) { vars += "hero_id,"; values += sHeroId + ",";}
		if (mStoreFlags.get(E_VITALITY)) { vars += "vitality,"; values += sVitality + ",";}
		if (mStoreFlags.get(E_HP)) { vars += "hp,"; values += sHp + ",";}
		if (mStoreFlags.get(E_MOVES)) { vars += "moves,"; values += sMoves + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO heros "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE heros SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM heros WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setArmyId(int aArmyId) {
		this.mStoreFlags.set(E_ARMYID);
		this.setSQLaction(2);
		this.sArmyId = aArmyId;
	}

	public void setHeroId(int aHeroId) {
		this.mStoreFlags.set(E_HEROID);
		this.setSQLaction(2);
		this.sHeroId = aHeroId;
	}

	public void setVitality(byte aVitality) {
		this.mStoreFlags.set(E_VITALITY);
		this.setSQLaction(2);
		this.sVitality = aVitality;
	}

	public void setHp(int aHp) {
		this.mStoreFlags.set(E_HP);
		this.setSQLaction(2);
		this.sHp = aHp;
	}

	public void setMoves(byte aMoves) {
		this.mStoreFlags.set(E_MOVES);
		this.setSQLaction(2);
		this.sMoves = aMoves;
	}


	public int getId() {
		return sId;
	}

	public int getArmyId() {
		return sArmyId;
	}

	public int getHeroId() {
		return sHeroId;
	}

	public byte getVitality() {
		return sVitality;
	}

	public int getHp() {
		return sHp;
	}

	public byte getMoves() {
		return sMoves;
	}
}

