package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;


//Object generated by zbyte's sql to java script
public class ACMessages {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sSenderId;
	private int sRecieverId;
	private byte sType;
	private int sContent;

	public static ACMessagesTable mTable;
	public static final short E_ID=0;
	public static final short E_SENDERID=1;
	public static final short E_RECIEVERID=2;
	public static final short E_TYPE=3;
	public static final short E_CONTENT=4;

	public ACMessages(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACMessages(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sSenderId = (int)Integer.parseInt(SQLRes.getObject(E_SENDERID).toString());
			sRecieverId = (int)Integer.parseInt(SQLRes.getObject(E_RECIEVERID).toString());
			sType = (byte)Integer.parseInt(SQLRes.getObject(E_TYPE).toString());
			sContent = (int)Integer.parseInt(SQLRes.getObject(E_CONTENT).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_SENDERID)) result += " sender_id="+sSenderId + ",";
		if (mStoreFlags.get(E_RECIEVERID)) result += " reciever_id="+sRecieverId + ",";
		if (mStoreFlags.get(E_TYPE)) result += " type="+sType + ",";
		if (mStoreFlags.get(E_CONTENT)) result += " content="+sContent + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_SENDERID)) { vars += "sender_id,"; values += sSenderId + ",";}
		if (mStoreFlags.get(E_RECIEVERID)) { vars += "reciever_id,"; values += sRecieverId + ",";}
		if (mStoreFlags.get(E_TYPE)) { vars += "type,"; values += sType + ",";}
		if (mStoreFlags.get(E_CONTENT)) { vars += "content,"; values += sContent + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO messages "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE messages SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM messages WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setSenderId(int aSenderId) {
		this.mStoreFlags.set(E_SENDERID);
		this.setSQLaction(2);
		this.sSenderId = aSenderId;
	}

	public void setRecieverId(int aRecieverId) {
		this.mStoreFlags.set(E_RECIEVERID);
		this.setSQLaction(2);
		this.sRecieverId = aRecieverId;
	}

	public void setType(byte aType) {
		this.mStoreFlags.set(E_TYPE);
		this.setSQLaction(2);
		this.sType = aType;
	}

	public void setContent(int aContent) {
		this.mStoreFlags.set(E_CONTENT);
		this.setSQLaction(2);
		this.sContent = aContent;
	}


	public int getId() {
		return sId;
	}

	public int getSenderId() {
		return sSenderId;
	}

	public int getRecieverId() {
		return sRecieverId;
	}

	public byte getType() {
		return sType;
	}

	public int getContent() {
		return sContent;
	}
}

