package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACMessagesTable extends ACMessagesList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACMessagesTable() {
	} 

	public void remove(ACMessages aACMessages) {
		aACMessages.setSQLaction(3);
		appendSQLsync(aACMessages);
		this.ACMessagesVector.remove(aACMessages);
	}

	public ACMessages create() {
		max_id++;
		ACMessages aACMessages = new ACMessages(max_id);
		ACMessagesVector.add(aACMessages); //bypass sort algorithm
		return aACMessages;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACMessages current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACMessages)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACMessages aACMessages) {
		SQLsyncObjects.push(aACMessages);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, sender_id, reciever_id, type, content FROM messages ORDER BY id");
			ACMessages loadedSQLACMessages;
			while (res.next()) {
				loadedSQLACMessages = new ACMessages(res);
				ACMessagesVector.add(loadedSQLACMessages); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

