package org.archcave.classes;
import java.util.Vector;
import org.archcave.libs.JHash;

//List generated by zbyte's sql to java script
public class ACPlayersList {
	protected Vector ACPlayersVector = new Vector();
	
	public void add(ACPlayers aACPlayers) {
		if (ACPlayersVector.size() == 0) {
			ACPlayersVector.add(0, aACPlayers);
			return;
		}
		int middle = (ACPlayersVector.size()-1)/2;
		int index = middle;
		ACPlayers current = (ACPlayers)ACPlayersVector.get(index);
		while ((index > 0)&&(current.getId() > aACPlayers.getId()))
		{
			index--;
			current = (ACPlayers)ACPlayersVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACPlayersVector.size() - 1 )&&(current.getId() < aACPlayers.getId()))
			{
				index++;
				current = (ACPlayers)ACPlayersVector.get(index);
			}
		}
		ACPlayersVector.add(index, aACPlayers);
	}
	
	public ACPlayers fetch(int aID) {
		if (ACPlayersVector.size() == 0) return null;
		int middle = (ACPlayersVector.size()-1)/2;
		int index = middle;
		ACPlayers current = (ACPlayers)ACPlayersVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACPlayers)ACPlayersVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACPlayersVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACPlayers)ACPlayersVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACPlayersVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACPlayers aACPlayers) {//done
		this.ACPlayersVector.remove(aACPlayers);
	}
	
	public int length() {//done
		return this.ACPlayersVector.size();
	}
	
	public ACPlayers get(int aNumber) {//done
		return (ACPlayers)ACPlayersVector.get(aNumber);
	}

	public ACPlayersList findByName(java.lang.String aName) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aName.equals(current.getName())) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByRulerId(int aRulerId) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aRulerId == current.getRulerId()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByChoicesHash(org.archcave.libs.JHash aChoicesHash) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aChoicesHash == current.getChoicesHash()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByPoliciesHash(org.archcave.libs.JHash aPoliciesHash) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aPoliciesHash == current.getPoliciesHash()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByTechHash(org.archcave.libs.JHash aTechHash) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aTechHash == current.getTechHash()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByAbilitiesHash(org.archcave.libs.JHash aAbilitiesHash) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aAbilitiesHash == current.getAbilitiesHash()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByEra(byte aEra) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aEra == current.getEra()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByCurrency(long aCurrency) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aCurrency == current.getCurrency()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByResearchInvest(int aResearchInvest) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aResearchInvest == current.getResearchInvest()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByCurrentResearchId(short aCurrentResearchId) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aCurrentResearchId == current.getCurrentResearchId()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByResearchPoints(int aResearchPoints) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aResearchPoints == current.getResearchPoints()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByHonor(byte aHonor) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aHonor == current.getHonor()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findBySecurityLevel(byte aSecurityLevel) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aSecurityLevel == current.getSecurityLevel()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByAlertness(byte aAlertness) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aAlertness == current.getAlertness()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByTurn(int aTurn) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aTurn == current.getTurn()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByNewsTurn(int aNewsTurn) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aNewsTurn == current.getNewsTurn()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByNewsProduction(int aNewsProduction) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aNewsProduction == current.getNewsProduction()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByNewsResearch(int aNewsResearch) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aNewsResearch == current.getNewsResearch()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}

	public ACPlayersList findByNewsPopulation(int aNewsPopulation) {
		ACPlayersList aACPlayersList = new ACPlayersList();
		ACPlayers current;
		for (int i = 0; i < this.ACPlayersVector.size(); i++) {
			current = (ACPlayers)this.ACPlayersVector.get(i);
			if (aNewsPopulation == current.getNewsPopulation()) {
				aACPlayersList.add(current);
			}
		}
		return aACPlayersList;
	}
}

