package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Table generated by zbyte's sql to java script
public class ACPlayersTable extends ACPlayersList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACPlayersTable() {
	} 

	public void remove(ACPlayers aACPlayers) {
		aACPlayers.setSQLaction(3);
		appendSQLsync(aACPlayers);
		this.ACPlayersVector.remove(aACPlayers);
	}

	public ACPlayers create() {
		max_id++;
		ACPlayers aACPlayers = new ACPlayers(max_id);
		ACPlayersVector.add(aACPlayers); //bypass sort algorithm
		return aACPlayers;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACPlayers current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACPlayers)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACPlayers aACPlayers) {
		SQLsyncObjects.push(aACPlayers);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, name, ruler_id, choices_hash, policies_hash, tech_hash, abilities_hash, era, currency, research_invest, current_research_id, research_points, honor, security_level, alertness, turn, news_turn, news_production, news_research, news_population FROM players ORDER BY id");
			ACPlayers loadedSQLACPlayers;
			while (res.next()) {
				loadedSQLACPlayers = new ACPlayers(res);
				ACPlayersVector.add(loadedSQLACPlayers); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

