package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACRelationsTable extends ACRelationsList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACRelationsTable() {
	} 

	public void remove(ACRelations aACRelations) {
		aACRelations.setSQLaction(3);
		appendSQLsync(aACRelations);
		this.ACRelationsVector.remove(aACRelations);
	}

	public ACRelations create() {
		max_id++;
		ACRelations aACRelations = new ACRelations(max_id);
		ACRelationsVector.add(aACRelations); //bypass sort algorithm
		return aACRelations;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACRelations current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACRelations)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACRelations aACRelations) {
		SQLsyncObjects.push(aACRelations);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, player1_id, player2_id, type FROM relations ORDER BY id");
			ACRelations loadedSQLACRelations;
			while (res.next()) {
				loadedSQLACRelations = new ACRelations(res);
				ACRelationsVector.add(loadedSQLACRelations); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

