package org.archcave.classes;
import java.util.Vector;


//List generated by zbyte's sql to java script
public class ACRelationsList {
	protected Vector ACRelationsVector = new Vector();
	
	public void add(ACRelations aACRelations) {
		if (ACRelationsVector.size() == 0) {
			ACRelationsVector.add(0, aACRelations);
			return;
		}
		int middle = (ACRelationsVector.size()-1)/2;
		int index = middle;
		ACRelations current = (ACRelations)ACRelationsVector.get(index);
		while ((index > 0)&&(current.getId() > aACRelations.getId()))
		{
			index--;
			current = (ACRelations)ACRelationsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACRelationsVector.size() - 1 )&&(current.getId() < aACRelations.getId()))
			{
				index++;
				current = (ACRelations)ACRelationsVector.get(index);
			}
		}
		ACRelationsVector.add(index, aACRelations);
	}
	
	public ACRelations fetch(int aID) {
		if (ACRelationsVector.size() == 0) return null;
		int middle = (ACRelationsVector.size()-1)/2;
		int index = middle;
		ACRelations current = (ACRelations)ACRelationsVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACRelations)ACRelationsVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACRelationsVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACRelations)ACRelationsVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACRelationsVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACRelations aACRelations) {//done
		this.ACRelationsVector.remove(aACRelations);
	}
	
	public int length() {//done
		return this.ACRelationsVector.size();
	}
	
	public ACRelations get(int aNumber) {//done
		return (ACRelations)ACRelationsVector.get(aNumber);
	}

	public ACRelationsList findByPlayer1Id(int aPlayer1Id) {
		ACRelationsList aACRelationsList = new ACRelationsList();
		ACRelations current;
		for (int i = 0; i < this.ACRelationsVector.size(); i++) {
			current = (ACRelations)this.ACRelationsVector.get(i);
			if (aPlayer1Id == current.getPlayer1Id()) {
				aACRelationsList.add(current);
			}
		}
		return aACRelationsList;
	}

	public ACRelationsList findByPlayer2Id(int aPlayer2Id) {
		ACRelationsList aACRelationsList = new ACRelationsList();
		ACRelations current;
		for (int i = 0; i < this.ACRelationsVector.size(); i++) {
			current = (ACRelations)this.ACRelationsVector.get(i);
			if (aPlayer2Id == current.getPlayer2Id()) {
				aACRelationsList.add(current);
			}
		}
		return aACRelationsList;
	}

	public ACRelationsList findByType(byte aType) {
		ACRelationsList aACRelationsList = new ACRelationsList();
		ACRelations current;
		for (int i = 0; i < this.ACRelationsVector.size(); i++) {
			current = (ACRelations)this.ACRelationsVector.get(i);
			if (aType == current.getType()) {
				aACRelationsList.add(current);
			}
		}
		return aACRelationsList;
	}
}

