package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;


//Table generated by zbyte's sql to java script
public class ACSquadsTable extends ACSquadsList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACSquadsTable() {
	} 

	public void remove(ACSquads aACSquads) {
		aACSquads.setSQLaction(3);
		appendSQLsync(aACSquads);
		this.ACSquadsVector.remove(aACSquads);
	}

	public ACSquads create() {
		max_id++;
		ACSquads aACSquads = new ACSquads(max_id);
		ACSquadsVector.add(aACSquads); //bypass sort algorithm
		return aACSquads;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACSquads current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACSquads)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACSquads aACSquads) {
		SQLsyncObjects.push(aACSquads);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, army_id, name, design_id, quantity, vitality, hp, commander_id, experience, moves FROM squads ORDER BY id");
			ACSquads loadedSQLACSquads;
			while (res.next()) {
				loadedSQLACSquads = new ACSquads(res);
				ACSquadsVector.add(loadedSQLACSquads); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

