package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Object generated by zbyte's sql to java script
public class ACTerritories {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private byte sType;
	private org.archcave.libs.JHash sResourcesHash;
	private org.archcave.libs.JHash sImprovementsHash;

	public static ACTerritoriesTable mTable;
	public static final short E_ID=0;
	public static final short E_TYPE=1;
	public static final short E_RESOURCESHASH=2;
	public static final short E_IMPROVEMENTSHASH=3;

	public ACTerritories(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACTerritories(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sType = (byte)Integer.parseInt(SQLRes.getObject(E_TYPE).toString());
			sResourcesHash = new JHash(SQLRes.getObject(E_RESOURCESHASH).toString());
			sImprovementsHash = new JHash(SQLRes.getObject(E_IMPROVEMENTSHASH).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_TYPE)) result += " type="+sType + ",";
		if (mStoreFlags.get(E_RESOURCESHASH)) result += " resources_hash="+sResourcesHash + ",";
		if (mStoreFlags.get(E_IMPROVEMENTSHASH)) result += " improvements_hash="+sImprovementsHash + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_TYPE)) { vars += "type,"; values += sType + ",";}
		if (mStoreFlags.get(E_RESOURCESHASH)) { vars += "resources_hash,"; values += sResourcesHash + ",";}
		if (mStoreFlags.get(E_IMPROVEMENTSHASH)) { vars += "improvements_hash,"; values += sImprovementsHash + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO territories "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE territories SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM territories WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setType(byte aType) {
		this.mStoreFlags.set(E_TYPE);
		this.setSQLaction(2);
		this.sType = aType;
	}

	public void setResourcesHash(org.archcave.libs.JHash aResourcesHash) {
		this.mStoreFlags.set(E_RESOURCESHASH);
		this.setSQLaction(2);
		this.sResourcesHash = aResourcesHash;
	}

	public void setImprovementsHash(org.archcave.libs.JHash aImprovementsHash) {
		this.mStoreFlags.set(E_IMPROVEMENTSHASH);
		this.setSQLaction(2);
		this.sImprovementsHash = aImprovementsHash;
	}


	public int getId() {
		return sId;
	}

	public byte getType() {
		return sType;
	}

	public org.archcave.libs.JHash getResourcesHash() {
		return sResourcesHash;
	}

	public org.archcave.libs.JHash getImprovementsHash() {
		return sImprovementsHash;
	}
}

