package org.archcave.classes;
import java.util.Vector;
import org.archcave.libs.JHash;

//List generated by zbyte's sql to java script
public class ACTerritoriesList {
	protected Vector ACTerritoriesVector = new Vector();
	
	public void add(ACTerritories aACTerritories) {
		if (ACTerritoriesVector.size() == 0) {
			ACTerritoriesVector.add(0, aACTerritories);
			return;
		}
		int middle = (ACTerritoriesVector.size()-1)/2;
		int index = middle;
		ACTerritories current = (ACTerritories)ACTerritoriesVector.get(index);
		while ((index > 0)&&(current.getId() > aACTerritories.getId()))
		{
			index--;
			current = (ACTerritories)ACTerritoriesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACTerritoriesVector.size() - 1 )&&(current.getId() < aACTerritories.getId()))
			{
				index++;
				current = (ACTerritories)ACTerritoriesVector.get(index);
			}
		}
		ACTerritoriesVector.add(index, aACTerritories);
	}
	
	public ACTerritories fetch(int aID) {
		if (ACTerritoriesVector.size() == 0) return null;
		int middle = (ACTerritoriesVector.size()-1)/2;
		int index = middle;
		ACTerritories current = (ACTerritories)ACTerritoriesVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACTerritories)ACTerritoriesVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACTerritoriesVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACTerritories)ACTerritoriesVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACTerritoriesVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACTerritories aACTerritories) {//done
		this.ACTerritoriesVector.remove(aACTerritories);
	}
	
	public int length() {//done
		return this.ACTerritoriesVector.size();
	}
	
	public ACTerritories get(int aNumber) {//done
		return (ACTerritories)ACTerritoriesVector.get(aNumber);
	}

	public ACTerritoriesList findByType(byte aType) {
		ACTerritoriesList aACTerritoriesList = new ACTerritoriesList();
		ACTerritories current;
		for (int i = 0; i < this.ACTerritoriesVector.size(); i++) {
			current = (ACTerritories)this.ACTerritoriesVector.get(i);
			if (aType == current.getType()) {
				aACTerritoriesList.add(current);
			}
		}
		return aACTerritoriesList;
	}

	public ACTerritoriesList findByResourcesHash(org.archcave.libs.JHash aResourcesHash) {
		ACTerritoriesList aACTerritoriesList = new ACTerritoriesList();
		ACTerritories current;
		for (int i = 0; i < this.ACTerritoriesVector.size(); i++) {
			current = (ACTerritories)this.ACTerritoriesVector.get(i);
			if (aResourcesHash == current.getResourcesHash()) {
				aACTerritoriesList.add(current);
			}
		}
		return aACTerritoriesList;
	}

	public ACTerritoriesList findByImprovementsHash(org.archcave.libs.JHash aImprovementsHash) {
		ACTerritoriesList aACTerritoriesList = new ACTerritoriesList();
		ACTerritories current;
		for (int i = 0; i < this.ACTerritoriesVector.size(); i++) {
			current = (ACTerritories)this.ACTerritoriesVector.get(i);
			if (aImprovementsHash == current.getImprovementsHash()) {
				aACTerritoriesList.add(current);
			}
		}
		return aACTerritoriesList;
	}
}

