package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Table generated by zbyte's sql to java script
public class ACTerritoriesTable extends ACTerritoriesList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACTerritoriesTable() {
	} 

	public void remove(ACTerritories aACTerritories) {
		aACTerritories.setSQLaction(3);
		appendSQLsync(aACTerritories);
		this.ACTerritoriesVector.remove(aACTerritories);
	}

	public ACTerritories create() {
		max_id++;
		ACTerritories aACTerritories = new ACTerritories(max_id);
		ACTerritoriesVector.add(aACTerritories); //bypass sort algorithm
		return aACTerritories;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACTerritories current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACTerritories)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACTerritories aACTerritories) {
		SQLsyncObjects.push(aACTerritories);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, type, resources_hash, improvements_hash FROM territories ORDER BY id");
			ACTerritories loadedSQLACTerritories;
			while (res.next()) {
				loadedSQLACTerritories = new ACTerritories(res);
				ACTerritoriesVector.add(loadedSQLACTerritories); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

