package org.archcave.classes;
import java.util.Vector;
import org.archcave.libs.JHash;

//List generated by zbyte's sql to java script
public class ACUsersList {
	protected Vector ACUsersVector = new Vector();
	
	public void add(ACUsers aACUsers) {
		if (ACUsersVector.size() == 0) {
			ACUsersVector.add(0, aACUsers);
			return;
		}
		int middle = (ACUsersVector.size()-1)/2;
		int index = middle;
		ACUsers current = (ACUsers)ACUsersVector.get(index);
		while ((index > 0)&&(current.getId() > aACUsers.getId()))
		{
			index--;
			current = (ACUsers)ACUsersVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACUsersVector.size() - 1 )&&(current.getId() < aACUsers.getId()))
			{
				index++;
				current = (ACUsers)ACUsersVector.get(index);
			}
		}
		ACUsersVector.add(index, aACUsers);
	}
	
	public ACUsers fetch(int aID) {
		if (ACUsersVector.size() == 0) return null;
		int middle = (ACUsersVector.size()-1)/2;
		int index = middle;
		ACUsers current = (ACUsers)ACUsersVector.get(index);
		while ((index > 0)&&(current.getId() > aID))
		{
			index--;
			current = (ACUsers)ACUsersVector.get(index);
		}
		if (index==middle)
		{
			while ((index < ACUsersVector.size() - 1 )&&(current.getId() < aID))
			{
				index++;
				current = (ACUsers)ACUsersVector.get(index);
			}
		}
		if (current.getId() == aID) {
			return current;
		}
		return null;
	}
	
	public void empty() {//done
		this.ACUsersVector.clear();
	}
	
	public void remove(int aID) {//done
		this.remove(this.fetch(aID));
	}
	
	public void remove(ACUsers aACUsers) {//done
		this.ACUsersVector.remove(aACUsers);
	}
	
	public int length() {//done
		return this.ACUsersVector.size();
	}
	
	public ACUsers get(int aNumber) {//done
		return (ACUsers)ACUsersVector.get(aNumber);
	}

	public ACUsersList findByPlayerId(int aPlayerId) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aPlayerId == current.getPlayerId()) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}

	public ACUsersList findByEmail(java.lang.String aEmail) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aEmail.equals(current.getEmail())) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}

	public ACUsersList findByName(java.lang.String aName) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aName.equals(current.getName())) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}

	public ACUsersList findByPassword(java.lang.String aPassword) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aPassword.equals(current.getPassword())) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}

	public ACUsersList findByVerification(long aVerification) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aVerification == current.getVerification()) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}

	public ACUsersList findByAdminHash(org.archcave.libs.JHash aAdminHash) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aAdminHash == current.getAdminHash()) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}

	public ACUsersList findByPreferenceHash(org.archcave.libs.JHash aPreferenceHash) {
		ACUsersList aACUsersList = new ACUsersList();
		ACUsers current;
		for (int i = 0; i < this.ACUsersVector.size(); i++) {
			current = (ACUsers)this.ACUsersVector.get(i);
			if (aPreferenceHash == current.getPreferenceHash()) {
				aACUsersList.add(current);
			}
		}
		return aACUsersList;
	}
}

