package org.archcave.classes;
import java.util.BitSet;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Object generated by zbyte's sql to java script
public class ACUsers {
	private BitSet mStoreFlags = new BitSet();
	private byte mSQLaction;
	private int sId;
	private int sPlayerId;
	private java.lang.String sEmail;
	private java.lang.String sName;
	private java.lang.String sPassword;
	private long sVerification;
	private org.archcave.libs.JHash sAdminHash;
	private org.archcave.libs.JHash sPreferenceHash;

	public static ACUsersTable mTable;
	public static final short E_ID=0;
	public static final short E_PLAYERID=1;
	public static final short E_EMAIL=2;
	public static final short E_NAME=3;
	public static final short E_PASSWORD=4;
	public static final short E_VERIFICATION=5;
	public static final short E_ADMINHASH=6;
	public static final short E_PREFERENCEHASH=7;

	public ACUsers(int aId) {
		sId = aId;
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(1);
	}

	public ACUsers(java.sql.ResultSet SQLRes) {
        	try {
			sId = (int)Integer.parseInt(SQLRes.getObject(E_ID).toString());
			sPlayerId = (int)Integer.parseInt(SQLRes.getObject(E_PLAYERID).toString());
			sEmail = SQLRes.getObject(E_EMAIL).toString();
			sName = SQLRes.getObject(E_NAME).toString();
			sPassword = SQLRes.getObject(E_PASSWORD).toString();
			sVerification = (long)Integer.parseInt(SQLRes.getObject(E_VERIFICATION).toString());
			sAdminHash = new JHash(SQLRes.getObject(E_ADMINHASH).toString());
			sPreferenceHash = new JHash(SQLRes.getObject(E_PREFERENCEHASH).toString());
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}

	private String getSQLupdatestatements() {
		String result = new String();
		if (mStoreFlags.get(E_PLAYERID)) result += " player_id="+sPlayerId + ",";
		if (mStoreFlags.get(E_EMAIL)) result += " email="+sEmail + ",";
		if (mStoreFlags.get(E_NAME)) result += " name="+sName + ",";
		if (mStoreFlags.get(E_PASSWORD)) result += " password="+sPassword + ",";
		if (mStoreFlags.get(E_VERIFICATION)) result += " verification="+sVerification + ",";
		if (mStoreFlags.get(E_ADMINHASH)) result += " admin_hash="+sAdminHash + ",";
		if (mStoreFlags.get(E_PREFERENCEHASH)) result += " preference_hash="+sPreferenceHash + ",";
		result = result.substring(0,result.length()-2);
		return result;
	}

	private String getSQLinsertstatements() {
		String vars = new String();
		String values = new String();
		if (mStoreFlags.get(E_ID)) { vars += "id,"; values += sId + ",";}
		if (mStoreFlags.get(E_PLAYERID)) { vars += "player_id,"; values += sPlayerId + ",";}
		if (mStoreFlags.get(E_EMAIL)) { vars += "email,"; values += sEmail + ",";}
		if (mStoreFlags.get(E_NAME)) { vars += "name,"; values += sName + ",";}
		if (mStoreFlags.get(E_PASSWORD)) { vars += "password,"; values += sPassword + ",";}
		if (mStoreFlags.get(E_VERIFICATION)) { vars += "verification,"; values += sVerification + ",";}
		if (mStoreFlags.get(E_ADMINHASH)) { vars += "admin_hash,"; values += sAdminHash + ",";}
		if (mStoreFlags.get(E_PREFERENCEHASH)) { vars += "preference_hash,"; values += sPreferenceHash + ",";}
		vars = vars.substring(0,vars.length()-2);
		values = values.substring(0,values.length()-2);
		return "("+vars+") VALUES ("+values+")";
	}

	public String getSQLquery() {
		String result = new String();
		switch (mSQLaction) {
			case 1: //insert
				result = "INSERT INTO users "+getSQLinsertstatements()+";";
				break;
			case 2: //update
				result = "UPDATE users SET "+getSQLupdatestatements()+" WHERE id="+sId+";";
				break;
			case 3: //delete
				result = "DELETE FROM users WHERE id="+sId+";";
				break;
		}
		mSQLaction = 0;
		mStoreFlags.clear();
		return result;
	}

	public void setSQLaction(byte aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = aSQLaction;
	}
	
	public void setSQLaction(int aSQLaction) {
		if (this.mSQLaction == 0) {
			mTable.appendSQLsync(this);
			this.mSQLaction = (byte)aSQLaction;
			return;
		}
		if (aSQLaction == 3) this.mSQLaction = (byte)aSQLaction;
	}

	public void setId(int aId) {
		this.mStoreFlags.set(E_ID);
		this.setSQLaction(2);
		this.sId = aId;
	}

	public void setPlayerId(int aPlayerId) {
		this.mStoreFlags.set(E_PLAYERID);
		this.setSQLaction(2);
		this.sPlayerId = aPlayerId;
	}

	public void setEmail(java.lang.String aEmail) {
		this.mStoreFlags.set(E_EMAIL);
		this.setSQLaction(2);
		this.sEmail = aEmail;
	}

	public void setName(java.lang.String aName) {
		this.mStoreFlags.set(E_NAME);
		this.setSQLaction(2);
		this.sName = aName;
	}

	public void setPassword(java.lang.String aPassword) {
		this.mStoreFlags.set(E_PASSWORD);
		this.setSQLaction(2);
		this.sPassword = aPassword;
	}

	public void setVerification(long aVerification) {
		this.mStoreFlags.set(E_VERIFICATION);
		this.setSQLaction(2);
		this.sVerification = aVerification;
	}

	public void setAdminHash(org.archcave.libs.JHash aAdminHash) {
		this.mStoreFlags.set(E_ADMINHASH);
		this.setSQLaction(2);
		this.sAdminHash = aAdminHash;
	}

	public void setPreferenceHash(org.archcave.libs.JHash aPreferenceHash) {
		this.mStoreFlags.set(E_PREFERENCEHASH);
		this.setSQLaction(2);
		this.sPreferenceHash = aPreferenceHash;
	}


	public int getId() {
		return sId;
	}

	public int getPlayerId() {
		return sPlayerId;
	}

	public java.lang.String getEmail() {
		return sEmail;
	}

	public java.lang.String getName() {
		return sName;
	}

	public java.lang.String getPassword() {
		return sPassword;
	}

	public long getVerification() {
		return sVerification;
	}

	public org.archcave.libs.JHash getAdminHash() {
		return sAdminHash;
	}

	public org.archcave.libs.JHash getPreferenceHash() {
		return sPreferenceHash;
	}
}

