package org.archcave.classes;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import org.archcave.libs.JStore;
import org.archcave.libs.JLog;
import org.archcave.libs.JHash;

//Table generated by zbyte's sql to java script
public class ACUsersTable extends ACUsersList implements JStore {

	private int max_id;
	private java.util.Stack SQLsyncObjects = new java.util.Stack();

	public ACUsersTable() {
	} 

	public void remove(ACUsers aACUsers) {
		aACUsers.setSQLaction(3);
		appendSQLsync(aACUsers);
		this.ACUsersVector.remove(aACUsers);
	}

	public ACUsers create() {
		max_id++;
		ACUsers aACUsers = new ACUsers(max_id);
		ACUsersVector.add(aACUsers); //bypass sort algorithm
		return aACUsers;
	}
	
	public void executeSQLqueries(java.sql.Statement SQLStatement) {
		ACUsers current;
		ResultSet res = null;
		try {
			while (!SQLsyncObjects.empty()) {
				current = (ACUsers)SQLsyncObjects.pop();
				res = SQLStatement.executeQuery(current.getSQLquery());
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
	
	public void appendSQLsync(ACUsers aACUsers) {
		SQLsyncObjects.push(aACUsers);
	}
	
	public void flushSQLsync() {
		SQLsyncObjects.clear();
	}

	public void load(java.sql.Statement SQLStatement) {
		try {
			ResultSet res = SQLStatement.executeQuery("SELECT id, player_id, email, name, password, verification, admin_hash, preference_hash FROM users ORDER BY id");
			ACUsers loadedSQLACUsers;
			while (res.next()) {
				loadedSQLACUsers = new ACUsers(res);
				ACUsersVector.add(loadedSQLACUsers); //bypass sort algorithm
			}
			if (res != null) {
				res.close();   
			}
		} catch (SQLException ex) {
			// handle any errors 
			JLog.log("SQLException: " + ex.getMessage()); 
			JLog.log("SQLState: " + ex.getSQLState()); 
			JLog.log("VendorError: " + ex.getErrorCode()); 
		}
	}
}

