CC=g++
CFLAGS=-g -fpermissive -Wall -Wno-write-strings
LIBDIRS=-L/usr/lib
LIBS=-static -lstdc++ 
INCLUDES=-I/usr/g++ -I/usr/include -I../include -I/usr/include/pth -I/usr/include/mariadb -I/usr/include/mysql
DEFINES=-DDEBUG

VPATH=$(HOME)src/libs/include

HEADERFILES=
CCFILES= database.cc sql.cc store.cc store.ct.cc mysql.pool.cc

CCOBJS=$(CCFILES:.cc=.o)

.cc.o:
	$(CC) -c $< $(CFLAGS) $(INCLUDES) $(DEFINES)

lib:$(CCOBJS)


clean:
	rm -f *.o 
